<auro-menuoption value="Aberdeen, SD (ABR-Aberdeen)" id="Aberdeen, SD (ABR-Aberdeen)" suggest="Aberdeen, SD (ABR-Aberdeen)">Aberdeen, SD (ABR-Aberdeen)</auro-menuoption>
<auro-menuoption value="Abilene, TX (ABI-Abilene Regional)" id="Abilene, TX (ABI-Abilene Regional)" suggest="Abilene, TX (ABI-Abilene Regional)">Abilene, TX (ABI-Abilene Regional)</auro-menuoption>
<auro-menuoption value="Acapulco, Mexico (ACA-Juan N. Alvarez)" id="Acapulco, Mexico (ACA-Juan N. Alvarez)" suggest="Acapulco, Mexico (ACA-Juan N. Alvarez)">Acapulco, Mexico (ACA-Juan N. Alvarez)</auro-menuoption>
<auro-menuoption value="Adak Island, AK (ADK-Adak Island)" id="Adak Island, AK (ADK-Adak Island)" suggest="Adak Island, AK (ADK-Adak Island)">Adak Island, AK (ADK-Adak Island)</auro-menuoption>
<auro-menuoption value="Aguascalientes, Mexico (AGU-Aguascalientes)" id="Aguascalientes, Mexico (AGU-Aguascalientes)" suggest="Aguascalientes, Mexico (AGU-Aguascalientes)">Aguascalientes, Mexico (AGU-Aguascalientes)</auro-menuoption>
<auro-menuoption value="Akron, OH (CAK-Akron/Canton Regional)" id="Akron, OH (CAK-Akron/Canton Regional)" suggest="Akron, OH (CAK-Akron/Canton Regional)">Akron, OH (CAK-Akron/Canton Regional)</auro-menuoption>
<auro-menuoption value="Albany, GA (ABY-Albany Dougherty County)" id="Albany, GA (ABY-Albany Dougherty County)" suggest="Albany, GA (ABY-Albany Dougherty County)">Albany, GA (ABY-Albany Dougherty County)</auro-menuoption>
<auro-menuoption value="Albany, NY (ALB-Albany County)" id="Albany, NY (ALB-Albany County)" suggest="Albany, NY (ALB-Albany County)">Albany, NY (ALB-Albany County)</auro-menuoption>
<auro-menuoption value="Albuquerque, NM (ABQ-Albuquerque Intl.)" id="Albuquerque, NM (ABQ-Albuquerque Intl.)" suggest="Albuquerque, NM (ABQ-Albuquerque Intl.)">Albuquerque, NM (ABQ-Albuquerque Intl.)</auro-menuoption>
<auro-menuoption value="Alexandria, LA (AEX-Alexandria Intl.)" id="Alexandria, LA (AEX-Alexandria Intl.)" suggest="Alexandria, LA (AEX-Alexandria Intl.)">Alexandria, LA (AEX-Alexandria Intl.)</auro-menuoption>
<auro-menuoption value="Allentown, PA (ABE-Allentown/Bethlehem/Easton)" id="Allentown, PA (ABE-Allentown/Bethlehem/Easton)" suggest="Allentown, PA (ABE-Allentown/Bethlehem/Easton)">Allentown, PA (ABE-Allentown/Bethlehem/Easton)</auro-menuoption>
<auro-menuoption value="Alpena, MI (APN-County Regional)" id="Alpena, MI (APN-County Regional)" suggest="Alpena, MI (APN-County Regional)">Alpena, MI (APN-County Regional)</auro-menuoption>
<auro-menuoption value="Amarillo, TX (AMA-Amarillo Intl.)" id="Amarillo, TX (AMA-Amarillo Intl.)" suggest="Amarillo, TX (AMA-Amarillo Intl.)">Amarillo, TX (AMA-Amarillo Intl.)</auro-menuoption>
<auro-menuoption value="Anchorage, AK (ANC-Anchorage Intl.)" id="Anchorage, AK (ANC-Anchorage Intl.)" suggest="Anchorage, AK (ANC-Anchorage Intl.)">Anchorage, AK (ANC-Anchorage Intl.)</auro-menuoption>
<auro-menuoption value="Aniak, AK (ANI-Aniak)" id="Aniak, AK (ANI-Aniak)" suggest="Aniak, AK (ANI-Aniak)">Aniak, AK (ANI-Aniak)</auro-menuoption>
<auro-menuoption value="Appleton, WI (ATW-Outagamie County)" id="Appleton, WI (ATW-Outagamie County)" suggest="Appleton, WI (ATW-Outagamie County)">Appleton, WI (ATW-Outagamie County)</auro-menuoption>
<auro-menuoption value="Arcata, CA (ACV-Arcata/Eureka)" id="Arcata, CA (ACV-Arcata/Eureka)" suggest="Arcata, CA (ACV-Arcata/Eureka)">Arcata, CA (ACV-Arcata/Eureka)</auro-menuoption>
<auro-menuoption value="Asheville, NC (AVL-Asheville Regional)" id="Asheville, NC (AVL-Asheville Regional)" suggest="Asheville, NC (AVL-Asheville Regional)">Asheville, NC (AVL-Asheville Regional)</auro-menuoption>
<auro-menuoption value="Aspen, CO (ASE-Sardy Field)" id="Aspen, CO (ASE-Sardy Field)" suggest="Aspen, CO (ASE-Sardy Field)">Aspen, CO (ASE-Sardy Field)</auro-menuoption>
<auro-menuoption value="Atlanta, GA (ATL-Hartsfield Intl.)" id="Atlanta, GA (ATL-Hartsfield Intl.)" suggest="Atlanta, GA (ATL-Hartsfield Intl.)">Atlanta, GA (ATL-Hartsfield Intl.)</auro-menuoption>
<auro-menuoption value="Augusta, GA (AGS-Augusta Bush Field)" id="Augusta, GA (AGS-Augusta Bush Field)" suggest="Augusta, GA (AGS-Augusta Bush Field)">Augusta, GA (AGS-Augusta Bush Field)</auro-menuoption>
<auro-menuoption value="Austin, TX (AUS-Austin/Bergstrom Intl.)" id="Austin, TX (AUS-Austin/Bergstrom Intl.)" suggest="Austin, TX (AUS-Austin/Bergstrom Intl.)">Austin, TX (AUS-Austin/Bergstrom Intl.)</auro-menuoption>
<auro-menuoption value="Bakersfield, CA (BFL-Bakersfield)" id="Bakersfield, CA (BFL-Bakersfield)" suggest="Bakersfield, CA (BFL-Bakersfield)">Bakersfield, CA (BFL-Bakersfield)</auro-menuoption>
<auro-menuoption value="Baltimore, MD (BWI-Baltimore Washington)" id="Baltimore, MD (BWI-Baltimore Washington)" suggest="Baltimore, MD (BWI-Baltimore Washington)">Baltimore, MD (BWI-Baltimore Washington)</auro-menuoption>
<auro-menuoption value="Bangor, ME (BGR-Bangor Intl.)" id="Bangor, ME (BGR-Bangor Intl.)" suggest="Bangor, ME (BGR-Bangor Intl.)">Bangor, ME (BGR-Bangor Intl.)</auro-menuoption>
<auro-menuoption value="Barrow, AK (BRW-Wiley Post/Will Rogers)" id="Barrow, AK (BRW-Wiley Post/Will Rogers)" suggest="Barrow, AK (BRW-Wiley Post/Will Rogers)">Barrow, AK (BRW-Wiley Post/Will Rogers)</auro-menuoption>
<auro-menuoption value="Baton Rouge, LA (BTR-Metropolitan)" id="Baton Rouge, LA (BTR-Metropolitan)" suggest="Baton Rouge, LA (BTR-Metropolitan)">Baton Rouge, LA (BTR-Metropolitan)</auro-menuoption>
<auro-menuoption value="Bay Area (QSF-All Airports)" id="Bay Area (QSF-All Airports)" suggest="Bay Area (QSF-All Airports)">Bay Area (QSF-All Airports)</auro-menuoption>
<auro-menuoption value="Bay Area (OAK-Oakland Intl.)" id="Bay Area (OAK-Oakland Intl.)" suggest="Bay Area (OAK-Oakland Intl.)">Bay Area (OAK-Oakland Intl.)</auro-menuoption>
<auro-menuoption value="Bay Area (SFO-San Francisco Intl.)" id="Bay Area (SFO-San Francisco Intl.)" suggest="Bay Area (SFO-San Francisco Intl.)">Bay Area (SFO-San Francisco Intl.)</auro-menuoption>
<auro-menuoption value="Bay Area (SJC-San Jose Intl.)" id="Bay Area (SJC-San Jose Intl.)" suggest="Bay Area (SJC-San Jose Intl.)">Bay Area (SJC-San Jose Intl.)</auro-menuoption>
<auro-menuoption value="Beaumont, TX (BPT-Jack Brooks Regional)" id="Beaumont, TX (BPT-Jack Brooks Regional)" suggest="Beaumont, TX (BPT-Jack Brooks Regional)">Beaumont, TX (BPT-Jack Brooks Regional)</auro-menuoption>
<auro-menuoption value="Belize City, Belize (BZE-Belize City)" id="Belize City, Belize (BZE-Belize City)" suggest="Belize City, Belize (BZE-Belize City)">Belize City, Belize (BZE-Belize City)</auro-menuoption>
<auro-menuoption value="Bellingham, WA (BLI-Bellingham Intl.)" id="Bellingham, WA (BLI-Bellingham Intl.)" suggest="Bellingham, WA (BLI-Bellingham Intl.)">Bellingham, WA (BLI-Bellingham Intl.)</auro-menuoption>
<auro-menuoption value="Bemidji, MN (BJI-Bemidji/Beltrami County)" id="Bemidji, MN (BJI-Bemidji/Beltrami County)" suggest="Bemidji, MN (BJI-Bemidji/Beltrami County)">Bemidji, MN (BJI-Bemidji/Beltrami County)</auro-menuoption>
<auro-menuoption value="Bend, OR (RDM-Redmond/Bend/Roberts Field)" id="Bend, OR (RDM-Redmond/Bend/Roberts Field)" suggest="Bend, OR (RDM-Redmond/Bend/Roberts Field)">Bend, OR (RDM-Redmond/Bend/Roberts Field)</auro-menuoption>
<auro-menuoption value="Bethel, AK (BET-Bethel Municipal)" id="Bethel, AK (BET-Bethel Municipal)" suggest="Bethel, AK (BET-Bethel Municipal)">Bethel, AK (BET-Bethel Municipal)</auro-menuoption>
<auro-menuoption value="Billings, MT (BIL-Logan Intl.)" id="Billings, MT (BIL-Logan Intl.)" suggest="Billings, MT (BIL-Logan Intl.)">Billings, MT (BIL-Logan Intl.)</auro-menuoption>
<auro-menuoption value="Biloxi, MS (GPT-Gulfport Biloxi)" id="Biloxi, MS (GPT-Gulfport Biloxi)" suggest="Biloxi, MS (GPT-Gulfport Biloxi)">Biloxi, MS (GPT-Gulfport Biloxi)</auro-menuoption>
<auro-menuoption value="Binghamton, NY (BGM-Edwin A. Link Field)" id="Binghamton, NY (BGM-Edwin A. Link Field)" suggest="Binghamton, NY (BGM-Edwin A. Link Field)">Binghamton, NY (BGM-Edwin A. Link Field)</auro-menuoption>
<auro-menuoption value="Birmingham, AL (BHM-Birmingham Intl.)" id="Birmingham, AL (BHM-Birmingham Intl.)" suggest="Birmingham, AL (BHM-Birmingham Intl.)">Birmingham, AL (BHM-Birmingham Intl.)</auro-menuoption>
<auro-menuoption value="Bismarck, ND (BIS-Bismarck Municipal)" id="Bismarck, ND (BIS-Bismarck Municipal)" suggest="Bismarck, ND (BIS-Bismarck Municipal)">Bismarck, ND (BIS-Bismarck Municipal)</auro-menuoption>
<auro-menuoption value="Bloomington, IL (BMI-Bloomington Normal)" id="Bloomington, IL (BMI-Bloomington Normal)" suggest="Bloomington, IL (BMI-Bloomington Normal)">Bloomington, IL (BMI-Bloomington Normal)</auro-menuoption>
<auro-menuoption value="Boise, ID (BOI-Boise Air Terminal)" id="Boise, ID (BOI-Boise Air Terminal)" suggest="Boise, ID (BOI-Boise Air Terminal)">Boise, ID (BOI-Boise Air Terminal)</auro-menuoption>
<auro-menuoption value="Boston, MA (BOS-Logan Intl.)" id="Boston, MA (BOS-Logan Intl.)" suggest="Boston, MA (BOS-Logan Intl.)">Boston, MA (BOS-Logan Intl.)</auro-menuoption>
<auro-menuoption value="Bozeman, MT (BZN-Gallatin Field)" id="Bozeman, MT (BZN-Gallatin Field)" suggest="Bozeman, MT (BZN-Gallatin Field)">Bozeman, MT (BZN-Gallatin Field)</auro-menuoption>
<auro-menuoption value="Brainerd, MN (BRD-Crow Wing)" id="Brainerd, MN (BRD-Crow Wing)" suggest="Brainerd, MN (BRD-Crow Wing)">Brainerd, MN (BRD-Crow Wing)</auro-menuoption>
<auro-menuoption value="Brownsville, TX (BRO-South Padre Island Intl.)" id="Brownsville, TX (BRO-South Padre Island Intl.)" suggest="Brownsville, TX (BRO-South Padre Island Intl.)">Brownsville, TX (BRO-South Padre Island Intl.)</auro-menuoption>
<auro-menuoption value="Brunswick, GA (BQK-Brunswick Glynco Jetport)" id="Brunswick, GA (BQK-Brunswick Glynco Jetport)" suggest="Brunswick, GA (BQK-Brunswick Glynco Jetport)">Brunswick, GA (BQK-Brunswick Glynco Jetport)</auro-menuoption>
<auro-menuoption value="Buffalo, NY (BUF-Buffalo Niagara Intl.)" id="Buffalo, NY (BUF-Buffalo Niagara Intl.)" suggest="Buffalo, NY (BUF-Buffalo Niagara Intl.)">Buffalo, NY (BUF-Buffalo Niagara Intl.)</auro-menuoption>
<auro-menuoption value="Burbank, CA (BUR-Burbank/Glendale/Pasadena)" id="Burbank, CA (BUR-Burbank/Glendale/Pasadena)" suggest="Burbank, CA (BUR-Burbank/Glendale/Pasadena)">Burbank, CA (BUR-Burbank/Glendale/Pasadena)</auro-menuoption>
<auro-menuoption value="Burlington, VT (BTV-Burlington Intl.)" id="Burlington, VT (BTV-Burlington Intl.)" suggest="Burlington, VT (BTV-Burlington Intl.)">Burlington, VT (BTV-Burlington Intl.)</auro-menuoption>
<auro-menuoption value="Butte, MT (BTM-Bert Mooney)" id="Butte, MT (BTM-Bert Mooney)" suggest="Butte, MT (BTM-Bert Mooney)">Butte, MT (BTM-Bert Mooney)</auro-menuoption>
<auro-menuoption value="Cabo San Lucas, Mexico (SJD-Los Cabos Intl.)" id="Cabo San Lucas, Mexico (SJD-Los Cabos Intl.)" suggest="Cabo San Lucas, Mexico (SJD-Los Cabos Intl.)">Cabo San Lucas, Mexico (SJD-Los Cabos Intl.)</auro-menuoption>
<auro-menuoption value="Calgary, AB, Canada (YYC-Calgary Intl.)" id="Calgary, AB, Canada (YYC-Calgary Intl.)" suggest="Calgary, AB, Canada (YYC-Calgary Intl.)">Calgary, AB, Canada (YYC-Calgary Intl.)</auro-menuoption>
<auro-menuoption value="Cancun, Mexico (CUN-Cancun Intl.)" id="Cancun, Mexico (CUN-Cancun Intl.)" suggest="Cancun, Mexico (CUN-Cancun Intl.)">Cancun, Mexico (CUN-Cancun Intl.)</auro-menuoption>
<auro-menuoption value="Canton, OH (CAK-Akron/Canton Regional)" id="Canton, OH (CAK-Akron/Canton Regional)" suggest="Canton, OH (CAK-Akron/Canton Regional)">Canton, OH (CAK-Akron/Canton Regional)</auro-menuoption>
<auro-menuoption value="Casper, WY (CPR-Natrona County Intl.)" id="Casper, WY (CPR-Natrona County Intl.)" suggest="Casper, WY (CPR-Natrona County Intl.)">Casper, WY (CPR-Natrona County Intl.)</auro-menuoption>
<auro-menuoption value="Cedar City, UT (CDC-Cedar City)" id="Cedar City, UT (CDC-Cedar City)" suggest="Cedar City, UT (CDC-Cedar City)">Cedar City, UT (CDC-Cedar City)</auro-menuoption>
<auro-menuoption value="Cedar Rapids, IA (CID-Cedar Rapids Municipal)" id="Cedar Rapids, IA (CID-Cedar Rapids Municipal)" suggest="Cedar Rapids, IA (CID-Cedar Rapids Municipal)">Cedar Rapids, IA (CID-Cedar Rapids Municipal)</auro-menuoption>
<auro-menuoption value="Champaign, IL (CMI-University Of Illinois/Willard)" id="Champaign, IL (CMI-University Of Illinois/Willard)" suggest="Champaign, IL (CMI-University Of Illinois/Willard)">Champaign, IL (CMI-University Of Illinois/Willard)</auro-menuoption>
<auro-menuoption value="Charleston, SC (CHS-Charleston Intl.)" id="Charleston, SC (CHS-Charleston Intl.)" suggest="Charleston, SC (CHS-Charleston Intl.)">Charleston, SC (CHS-Charleston Intl.)</auro-menuoption>
<auro-menuoption value="Charleston, WV (CRW-Yeager)" id="Charleston, WV (CRW-Yeager)" suggest="Charleston, WV (CRW-Yeager)">Charleston, WV (CRW-Yeager)</auro-menuoption>
<auro-menuoption value="Charlotte, NC (CLT-Douglas Intl.)" id="Charlotte, NC (CLT-Douglas Intl.)" suggest="Charlotte, NC (CLT-Douglas Intl.)">Charlotte, NC (CLT-Douglas Intl.)</auro-menuoption>
<auro-menuoption value="Charlottesville, VA (CHO-Charlottesville)" id="Charlottesville, VA (CHO-Charlottesville)" suggest="Charlottesville, VA (CHO-Charlottesville)">Charlottesville, VA (CHO-Charlottesville)</auro-menuoption>
<auro-menuoption value="Chattanooga, TN (CHA-Lovell Field)" id="Chattanooga, TN (CHA-Lovell Field)" suggest="Chattanooga, TN (CHA-Lovell Field)">Chattanooga, TN (CHA-Lovell Field)</auro-menuoption>
<auro-menuoption value="Chetumal, Mexico (CTM-Chetumal)" id="Chetumal, Mexico (CTM-Chetumal)" suggest="Chetumal, Mexico (CTM-Chetumal)">Chetumal, Mexico (CTM-Chetumal)</auro-menuoption>
<auro-menuoption value="Chicago, IL (CHI-All Airports)" id="Chicago, IL (CHI-All Airports)" suggest="Chicago, IL (CHI-All Airports)">Chicago, IL (CHI-All Airports)</auro-menuoption>
<auro-menuoption value="Chicago, IL (MDW-Midway)" id="Chicago, IL (MDW-Midway)" suggest="Chicago, IL (MDW-Midway)">Chicago, IL (MDW-Midway)</auro-menuoption>
<auro-menuoption value="Chicago, IL (ORD-O'Hare)" id="Chicago, IL (ORD-O'Hare)" suggest="Chicago, IL (ORD-O'Hare)">Chicago, IL (ORD-O'Hare)</auro-menuoption>
<auro-menuoption value="Chihuahua, Mexico (CUU-Gral Roberto Fierro Villalobos)" id="Chihuahua, Mexico (CUU-Gral Roberto Fierro Villalobos)" suggest="Chihuahua, Mexico (CUU-Gral Roberto Fierro Villalobos)">Chihuahua, Mexico (CUU-Gral Roberto Fierro Villalobos)</auro-menuoption>
<auro-menuoption value="Cincinnati, OH (CVG-Cincinnati N. Ky.)" id="Cincinnati, OH (CVG-Cincinnati N. Ky.)" suggest="Cincinnati, OH (CVG-Cincinnati N. Ky.)">Cincinnati, OH (CVG-Cincinnati N. Ky.)</auro-menuoption>
<auro-menuoption value="Cleveland, OH (CLE-Hopkins Intl.)" id="Cleveland, OH (CLE-Hopkins Intl.)" suggest="Cleveland, OH (CLE-Hopkins Intl.)">Cleveland, OH (CLE-Hopkins Intl.)</auro-menuoption>
<auro-menuoption value="Cold Bay, AK (CDB-Cold Bay)" id="Cold Bay, AK (CDB-Cold Bay)" suggest="Cold Bay, AK (CDB-Cold Bay)">Cold Bay, AK (CDB-Cold Bay)</auro-menuoption>
<auro-menuoption value="College Station, TX (CLL-Easterwood)" id="College Station, TX (CLL-Easterwood)" suggest="College Station, TX (CLL-Easterwood)">College Station, TX (CLL-Easterwood)</auro-menuoption>
<auro-menuoption value="Colorado Springs, CO (COS-Colorado Springs)" id="Colorado Springs, CO (COS-Colorado Springs)" suggest="Colorado Springs, CO (COS-Colorado Springs)">Colorado Springs, CO (COS-Colorado Springs)</auro-menuoption>
<auro-menuoption value="Columbia, MO (COU-Columbia Regional)" id="Columbia, MO (COU-Columbia Regional)" suggest="Columbia, MO (COU-Columbia Regional)">Columbia, MO (COU-Columbia Regional)</auro-menuoption>
<auro-menuoption value="Columbia, SC (CAE-Metropolitan)" id="Columbia, SC (CAE-Metropolitan)" suggest="Columbia, SC (CAE-Metropolitan)">Columbia, SC (CAE-Metropolitan)</auro-menuoption>
<auro-menuoption value="Columbus, GA (CSG-Columbus Metropolitan)" id="Columbus, GA (CSG-Columbus Metropolitan)" suggest="Columbus, GA (CSG-Columbus Metropolitan)">Columbus, GA (CSG-Columbus Metropolitan)</auro-menuoption>
<auro-menuoption value="Columbus, MS (GTR-Golden Triangle)" id="Columbus, MS (GTR-Golden Triangle)" suggest="Columbus, MS (GTR-Golden Triangle)">Columbus, MS (GTR-Golden Triangle)</auro-menuoption>
<auro-menuoption value="Columbus, OH (CMH-John Glenn Columbus Intl.)" id="Columbus, OH (CMH-John Glenn Columbus Intl.)" suggest="Columbus, OH (CMH-John Glenn Columbus Intl.)">Columbus, OH (CMH-John Glenn Columbus Intl.)</auro-menuoption>
<auro-menuoption value="Cordova, AK (CDV-Mudhole Smith)" id="Cordova, AK (CDV-Mudhole Smith)" suggest="Cordova, AK (CDV-Mudhole Smith)">Cordova, AK (CDV-Mudhole Smith)</auro-menuoption>
<auro-menuoption value="Corpus Christi, TX (CRP-Corpus Christi Intl.)" id="Corpus Christi, TX (CRP-Corpus Christi Intl.)" suggest="Corpus Christi, TX (CRP-Corpus Christi Intl.)">Corpus Christi, TX (CRP-Corpus Christi Intl.)</auro-menuoption>
<auro-menuoption value="Cozumel, Mexico (CZM-Cozumel Intl.)" id="Cozumel, Mexico (CZM-Cozumel Intl.)" suggest="Cozumel, Mexico (CZM-Cozumel Intl.)">Cozumel, Mexico (CZM-Cozumel Intl.)</auro-menuoption>
<auro-menuoption value="Crested Butte, CO (GUC-Gunnison)" id="Crested Butte, CO (GUC-Gunnison)" suggest="Crested Butte, CO (GUC-Gunnison)">Crested Butte, CO (GUC-Gunnison)</auro-menuoption>
<auro-menuoption value="Culiacan, Mexico (CUL-Culiacan)" id="Culiacan, Mexico (CUL-Culiacan)" suggest="Culiacan, Mexico (CUL-Culiacan)">Culiacan, Mexico (CUL-Culiacan)</auro-menuoption>
<auro-menuoption value="Dallas, TX (DAL-Love Field)" id="Dallas, TX (DAL-Love Field)" suggest="Dallas, TX (DAL-Love Field)">Dallas, TX (DAL-Love Field)</auro-menuoption>
<auro-menuoption value="Dallas-Ft. Worth, TX (All Airports)" id="Dallas-Ft. Worth, TX (All Airports)" suggest="Dallas-Ft. Worth, TX (All Airports)">Dallas-Ft. Worth, TX (All Airports)</auro-menuoption>
<auro-menuoption value="Dallas-Ft. Worth, TX (DAL-Love Field)" id="Dallas-Ft. Worth, TX (DAL-Love Field)" suggest="Dallas-Ft. Worth, TX (DAL-Love Field)">Dallas-Ft. Worth, TX (DAL-Love Field)</auro-menuoption>
<auro-menuoption value="Dallas-Ft. Worth, TX (DFW-Dallas/Fort Worth Intl.)" id="Dallas-Ft. Worth, TX (DFW-Dallas/Fort Worth Intl.)" suggest="Dallas-Ft. Worth, TX (DFW-Dallas/Fort Worth Intl.)">Dallas-Ft. Worth, TX (DFW-Dallas/Fort Worth Intl.)</auro-menuoption>
<auro-menuoption value="Dayton, OH (DAY-Dayton Intl.)" id="Dayton, OH (DAY-Dayton Intl.)" suggest="Dayton, OH (DAY-Dayton Intl.)">Dayton, OH (DAY-Dayton Intl.)</auro-menuoption>
<auro-menuoption value="Daytona Beach, FL (DAB-Daytona Beach Intl.)" id="Daytona Beach, FL (DAB-Daytona Beach Intl.)" suggest="Daytona Beach, FL (DAB-Daytona Beach Intl.)">Daytona Beach, FL (DAB-Daytona Beach Intl.)</auro-menuoption>
<auro-menuoption value="Del Rio, TX (DRT-Del Rio Intl.)" id="Del Rio, TX (DRT-Del Rio Intl.)" suggest="Del Rio, TX (DRT-Del Rio Intl.)">Del Rio, TX (DRT-Del Rio Intl.)</auro-menuoption>
<auro-menuoption value="Denver, CO (DEN-Denver Intl.)" id="Denver, CO (DEN-Denver Intl.)" suggest="Denver, CO (DEN-Denver Intl.)">Denver, CO (DEN-Denver Intl.)</auro-menuoption>
<auro-menuoption value="Des Moines, IA (DSM-Des Moines Intl.)" id="Des Moines, IA (DSM-Des Moines Intl.)" suggest="Des Moines, IA (DSM-Des Moines Intl.)">Des Moines, IA (DSM-Des Moines Intl.)</auro-menuoption>
<auro-menuoption value="Detroit, MI (DTW-Wayne County)" id="Detroit, MI (DTW-Wayne County)" suggest="Detroit, MI (DTW-Wayne County)">Detroit, MI (DTW-Wayne County)</auro-menuoption>
<auro-menuoption value="Dillingham, AK (DLG-Dillingham)" id="Dillingham, AK (DLG-Dillingham)" suggest="Dillingham, AK (DLG-Dillingham)">Dillingham, AK (DLG-Dillingham)</auro-menuoption>
<auro-menuoption value="Dothan, AL (DHN-Dothan)" id="Dothan, AL (DHN-Dothan)" suggest="Dothan, AL (DHN-Dothan)">Dothan, AL (DHN-Dothan)</auro-menuoption>
<auro-menuoption value="Dubuque, IA (DBQ-Dubuque Regional)" id="Dubuque, IA (DBQ-Dubuque Regional)" suggest="Dubuque, IA (DBQ-Dubuque Regional)">Dubuque, IA (DBQ-Dubuque Regional)</auro-menuoption>
<auro-menuoption value="Duluth, MN (DLH-Duluth Intl.)" id="Duluth, MN (DLH-Duluth Intl.)" suggest="Duluth, MN (DLH-Duluth Intl.)">Duluth, MN (DLH-Duluth Intl.)</auro-menuoption>
<auro-menuoption value="Durango, CO (DRO-La Plata Field)" id="Durango, CO (DRO-La Plata Field)" suggest="Durango, CO (DRO-La Plata Field)">Durango, CO (DRO-La Plata Field)</auro-menuoption>
<auro-menuoption value="Durango, Mexico (DGO-Durango)" id="Durango, Mexico (DGO-Durango)" suggest="Durango, Mexico (DGO-Durango)">Durango, Mexico (DGO-Durango)</auro-menuoption>
<auro-menuoption value="Dutch Harbor, AK (DUT-Dutch Harbor)" id="Dutch Harbor, AK (DUT-Dutch Harbor)" suggest="Dutch Harbor, AK (DUT-Dutch Harbor)">Dutch Harbor, AK (DUT-Dutch Harbor)</auro-menuoption>
<auro-menuoption value="Edmonton, AB, Canada (YEG-Edmonton Intl.)" id="Edmonton, AB, Canada (YEG-Edmonton Intl.)" suggest="Edmonton, AB, Canada (YEG-Edmonton Intl.)">Edmonton, AB, Canada (YEG-Edmonton Intl.)</auro-menuoption>
<auro-menuoption value="El Paso, TX (ELP-El Paso Intl.)" id="El Paso, TX (ELP-El Paso Intl.)" suggest="El Paso, TX (ELP-El Paso Intl.)">El Paso, TX (ELP-El Paso Intl.)</auro-menuoption>
<auro-menuoption value="Elko, NV (EKO-Elko)" id="Elko, NV (EKO-Elko)" suggest="Elko, NV (EKO-Elko)">Elko, NV (EKO-Elko)</auro-menuoption>
<auro-menuoption value="Elmira, NY (ELM-Elmira/Corning Regional)" id="Elmira, NY (ELM-Elmira/Corning Regional)" suggest="Elmira, NY (ELM-Elmira/Corning Regional)">Elmira, NY (ELM-Elmira/Corning Regional)</auro-menuoption>
<auro-menuoption value="Erie, PA (ERI-Erie Intl.)" id="Erie, PA (ERI-Erie Intl.)" suggest="Erie, PA (ERI-Erie Intl.)">Erie, PA (ERI-Erie Intl.)</auro-menuoption>
<auro-menuoption value="Escanaba, MI (ESC-Escanaba)" id="Escanaba, MI (ESC-Escanaba)" suggest="Escanaba, MI (ESC-Escanaba)">Escanaba, MI (ESC-Escanaba)</auro-menuoption>
<auro-menuoption value="Eugene, OR (EUG-Mahlon Sweet Field)" id="Eugene, OR (EUG-Mahlon Sweet Field)" suggest="Eugene, OR (EUG-Mahlon Sweet Field)">Eugene, OR (EUG-Mahlon Sweet Field)</auro-menuoption>
<auro-menuoption value="Eureka, CA (ACV-Arcata/Eureka)" id="Eureka, CA (ACV-Arcata/Eureka)" suggest="Eureka, CA (ACV-Arcata/Eureka)">Eureka, CA (ACV-Arcata/Eureka)</auro-menuoption>
<auro-menuoption value="Evansville, IN (EVV-Dress Regional)" id="Evansville, IN (EVV-Dress Regional)" suggest="Evansville, IN (EVV-Dress Regional)">Evansville, IN (EVV-Dress Regional)</auro-menuoption>
<auro-menuoption value="Everett, WA (PAE-Paine Field)" id="Everett, WA (PAE-Paine Field)" suggest="Everett, WA (PAE-Paine Field)">Everett, WA (PAE-Paine Field)</auro-menuoption>
<auro-menuoption value="Fairbanks, AK (FAI-Fairbanks Intl.)" id="Fairbanks, AK (FAI-Fairbanks Intl.)" suggest="Fairbanks, AK (FAI-Fairbanks Intl.)">Fairbanks, AK (FAI-Fairbanks Intl.)</auro-menuoption>
<auro-menuoption value="Fargo, ND (FAR-Hector)" id="Fargo, ND (FAR-Hector)" suggest="Fargo, ND (FAR-Hector)">Fargo, ND (FAR-Hector)</auro-menuoption>
<auro-menuoption value="Fayetteville, AR (XNA-Northwest Arkansas Regional)" id="Fayetteville, AR (XNA-Northwest Arkansas Regional)" suggest="Fayetteville, AR (XNA-Northwest Arkansas Regional)">Fayetteville, AR (XNA-Northwest Arkansas Regional)</auro-menuoption>
<auro-menuoption value="Fayetteville, NC (FAY-Fayetteville Municipal)" id="Fayetteville, NC (FAY-Fayetteville Municipal)" suggest="Fayetteville, NC (FAY-Fayetteville Municipal)">Fayetteville, NC (FAY-Fayetteville Municipal)</auro-menuoption>
<auro-menuoption value="Flagstaff, AZ (FLG-Flagstaff)" id="Flagstaff, AZ (FLG-Flagstaff)" suggest="Flagstaff, AZ (FLG-Flagstaff)">Flagstaff, AZ (FLG-Flagstaff)</auro-menuoption>
<auro-menuoption value="Flint, MI (FNT-Bishop Intl.)" id="Flint, MI (FNT-Bishop Intl.)" suggest="Flint, MI (FNT-Bishop Intl.)">Flint, MI (FNT-Bishop Intl.)</auro-menuoption>
<auro-menuoption value="Florence, SC (FLO-Florence)" id="Florence, SC (FLO-Florence)" suggest="Florence, SC (FLO-Florence)">Florence, SC (FLO-Florence)</auro-menuoption>
<auro-menuoption value="Fort Lauderdale, FL (FLL-Hollywood Intl.)" id="Fort Lauderdale, FL (FLL-Hollywood Intl.)" suggest="Fort Lauderdale, FL (FLL-Hollywood Intl.)">Fort Lauderdale, FL (FLL-Hollywood Intl.)</auro-menuoption>
<auro-menuoption value="Fort Myers, FL (RSW-Southwest Florida Regional)" id="Fort Myers, FL (RSW-Southwest Florida Regional)" suggest="Fort Myers, FL (RSW-Southwest Florida Regional)">Fort Myers, FL (RSW-Southwest Florida Regional)</auro-menuoption>
<auro-menuoption value="Fort Smith, AR (FSM-Fort Smith Regional)" id="Fort Smith, AR (FSM-Fort Smith Regional)" suggest="Fort Smith, AR (FSM-Fort Smith Regional)">Fort Smith, AR (FSM-Fort Smith Regional)</auro-menuoption>
<auro-menuoption value="Fort Walton Beach, FL (VPS-Okaloosa County)" id="Fort Walton Beach, FL (VPS-Okaloosa County)" suggest="Fort Walton Beach, FL (VPS-Okaloosa County)">Fort Walton Beach, FL (VPS-Okaloosa County)</auro-menuoption>
<auro-menuoption value="Fort Wayne, IN (FWA-Baer Field)" id="Fort Wayne, IN (FWA-Baer Field)" suggest="Fort Wayne, IN (FWA-Baer Field)">Fort Wayne, IN (FWA-Baer Field)</auro-menuoption>
<auro-menuoption value="Fresno, CA (FAT-Fresno Air Terminal)" id="Fresno, CA (FAT-Fresno Air Terminal)" suggest="Fresno, CA (FAT-Fresno Air Terminal)">Fresno, CA (FAT-Fresno Air Terminal)</auro-menuoption>
<auro-menuoption value="Gainesville, FL (GNV-Gainesville)" id="Gainesville, FL (GNV-Gainesville)" suggest="Gainesville, FL (GNV-Gainesville)">Gainesville, FL (GNV-Gainesville)</auro-menuoption>
<auro-menuoption value="Garden City, KS (GCK-Garden City)" id="Garden City, KS (GCK-Garden City)" suggest="Garden City, KS (GCK-Garden City)">Garden City, KS (GCK-Garden City)</auro-menuoption>
<auro-menuoption value="Glacier Bay, AK (GST-Gustavus)" id="Glacier Bay, AK (GST-Gustavus)" suggest="Glacier Bay, AK (GST-Gustavus)">Glacier Bay, AK (GST-Gustavus)</auro-menuoption>
<auro-menuoption value="Grand Forks, ND (GFK-Grand Forks Intl.)" id="Grand Forks, ND (GFK-Grand Forks Intl.)" suggest="Grand Forks, ND (GFK-Grand Forks Intl.)">Grand Forks, ND (GFK-Grand Forks Intl.)</auro-menuoption>
<auro-menuoption value="Grand Island, NE (GRI-Grand Island)" id="Grand Island, NE (GRI-Grand Island)" suggest="Grand Island, NE (GRI-Grand Island)">Grand Island, NE (GRI-Grand Island)</auro-menuoption>
<auro-menuoption value="Grand Junction, CO (GJT-Grand Junction)" id="Grand Junction, CO (GJT-Grand Junction)" suggest="Grand Junction, CO (GJT-Grand Junction)">Grand Junction, CO (GJT-Grand Junction)</auro-menuoption>
<auro-menuoption value="Grand Rapids, MI (GRR-Gerald R. Ford Intl.)" id="Grand Rapids, MI (GRR-Gerald R. Ford Intl.)" suggest="Grand Rapids, MI (GRR-Gerald R. Ford Intl.)">Grand Rapids, MI (GRR-Gerald R. Ford Intl.)</auro-menuoption>
<auro-menuoption value="Great Falls, MT (GTF-Great Falls Intl.)" id="Great Falls, MT (GTF-Great Falls Intl.)" suggest="Great Falls, MT (GTF-Great Falls Intl.)">Great Falls, MT (GTF-Great Falls Intl.)</auro-menuoption>
<auro-menuoption value="Green Bay, WI (GRB-Austin Straubel Intl.)" id="Green Bay, WI (GRB-Austin Straubel Intl.)" suggest="Green Bay, WI (GRB-Austin Straubel Intl.)">Green Bay, WI (GRB-Austin Straubel Intl.)</auro-menuoption>
<auro-menuoption value="Greensboro, NC (GSO-Piedmont Triad Intl.)" id="Greensboro, NC (GSO-Piedmont Triad Intl.)" suggest="Greensboro, NC (GSO-Piedmont Triad Intl.)">Greensboro, NC (GSO-Piedmont Triad Intl.)</auro-menuoption>
<auro-menuoption value="Greenville, NC (PGV-Greenville)" id="Greenville, NC (PGV-Greenville)" suggest="Greenville, NC (PGV-Greenville)">Greenville, NC (PGV-Greenville)</auro-menuoption>
<auro-menuoption value="Greenville, SC (GSP-Greenville)" id="Greenville, SC (GSP-Greenville)" suggest="Greenville, SC (GSP-Greenville)">Greenville, SC (GSP-Greenville)</auro-menuoption>
<auro-menuoption value="Guadalajara, Mexico (GDL-Miguel Hidalgo)" id="Guadalajara, Mexico (GDL-Miguel Hidalgo)" suggest="Guadalajara, Mexico (GDL-Miguel Hidalgo)">Guadalajara, Mexico (GDL-Miguel Hidalgo)</auro-menuoption>
<auro-menuoption value="Gulfport, MS (GPT-Gulfport Biloxi)" id="Gulfport, MS (GPT-Gulfport Biloxi)" suggest="Gulfport, MS (GPT-Gulfport Biloxi)">Gulfport, MS (GPT-Gulfport Biloxi)</auro-menuoption>
<auro-menuoption value="Gunnison, CO (GUC-Gunnison)" id="Gunnison, CO (GUC-Gunnison)" suggest="Gunnison, CO (GUC-Gunnison)">Gunnison, CO (GUC-Gunnison)</auro-menuoption>
<auro-menuoption value="Gustavus, AK (GST-Gustavus)" id="Gustavus, AK (GST-Gustavus)" suggest="Gustavus, AK (GST-Gustavus)">Gustavus, AK (GST-Gustavus)</auro-menuoption>
<auro-menuoption value="Halifax, NS, Canada (YHZ-Halifax Intl.)" id="Halifax, NS, Canada (YHZ-Halifax Intl.)" suggest="Halifax, NS, Canada (YHZ-Halifax Intl.)">Halifax, NS, Canada (YHZ-Halifax Intl.)</auro-menuoption>
<auro-menuoption value="Harlingen, TX (HRL-Valley Intl.)" id="Harlingen, TX (HRL-Valley Intl.)" suggest="Harlingen, TX (HRL-Valley Intl.)">Harlingen, TX (HRL-Valley Intl.)</auro-menuoption>
<auro-menuoption value="Harrisburg, PA (MDT-Harrisburg Intl.)" id="Harrisburg, PA (MDT-Harrisburg Intl.)" suggest="Harrisburg, PA (MDT-Harrisburg Intl.)">Harrisburg, PA (MDT-Harrisburg Intl.)</auro-menuoption>
<auro-menuoption value="Hartford, CT (BDL-Bradley Intl.)" id="Hartford, CT (BDL-Bradley Intl.)" suggest="Hartford, CT (BDL-Bradley Intl.)">Hartford, CT (BDL-Bradley Intl.)</auro-menuoption>
<auro-menuoption value="Helena, MT (HLN-Helena Regional)" id="Helena, MT (HLN-Helena Regional)" suggest="Helena, MT (HLN-Helena Regional)">Helena, MT (HLN-Helena Regional)</auro-menuoption>
<auro-menuoption value="Hermosillo, Mexico (HMO-Hermosillo)" id="Hermosillo, Mexico (HMO-Hermosillo)" suggest="Hermosillo, Mexico (HMO-Hermosillo)">Hermosillo, Mexico (HMO-Hermosillo)</auro-menuoption>
<auro-menuoption value="Hibbing, MN (HIB-Hibbing/Chisholm)" id="Hibbing, MN (HIB-Hibbing/Chisholm)" suggest="Hibbing, MN (HIB-Hibbing/Chisholm)">Hibbing, MN (HIB-Hibbing/Chisholm)</auro-menuoption>
<auro-menuoption value="Hilton Head Island, SC (HHH-Hilton Head Island)" id="Hilton Head Island, SC (HHH-Hilton Head Island)" suggest="Hilton Head Island, SC (HHH-Hilton Head Island)">Hilton Head Island, SC (HHH-Hilton Head Island)</auro-menuoption>
<auro-menuoption value="Homer, AK (HOM-Homer)" id="Homer, AK (HOM-Homer)" suggest="Homer, AK (HOM-Homer)">Homer, AK (HOM-Homer)</auro-menuoption>
<auro-menuoption value="Honolulu, HI (HNL-Honolulu Intl.)" id="Honolulu, HI (HNL-Honolulu Intl.)" suggest="Honolulu, HI (HNL-Honolulu Intl.)">Honolulu, HI (HNL-Honolulu Intl.)</auro-menuoption>
<auro-menuoption value="Houston, TX (QHO-All Airports)" id="Houston, TX (QHO-All Airports)" suggest="Houston, TX (QHO-All Airports)">Houston, TX (QHO-All Airports)</auro-menuoption>
<auro-menuoption value="Houston, TX (HOU-Houston Hobby)" id="Houston, TX (HOU-Houston Hobby)" suggest="Houston, TX (HOU-Houston Hobby)">Houston, TX (HOU-Houston Hobby)</auro-menuoption>
<auro-menuoption value="Houston, TX (IAH-Houston Bush Intercontinental)" id="Houston, TX (IAH-Houston Bush Intercontinental)" suggest="Houston, TX (IAH-Houston Bush Intercontinental)">Houston, TX (IAH-Houston Bush Intercontinental)</auro-menuoption>
<auro-menuoption value="Huatulco, Mexico (HUX-Huatulco)" id="Huatulco, Mexico (HUX-Huatulco)" suggest="Huatulco, Mexico (HUX-Huatulco)">Huatulco, Mexico (HUX-Huatulco)</auro-menuoption>
<auro-menuoption value="Huntington, WV (HTS-Huntington)" id="Huntington, WV (HTS-Huntington)" suggest="Huntington, WV (HTS-Huntington)">Huntington, WV (HTS-Huntington)</auro-menuoption>
<auro-menuoption value="Huntsville, AL (HSV-Madison County)" id="Huntsville, AL (HSV-Madison County)" suggest="Huntsville, AL (HSV-Madison County)">Huntsville, AL (HSV-Madison County)</auro-menuoption>
<auro-menuoption value="Idaho Falls, ID (IDA-Fanning Field)" id="Idaho Falls, ID (IDA-Fanning Field)" suggest="Idaho Falls, ID (IDA-Fanning Field)">Idaho Falls, ID (IDA-Fanning Field)</auro-menuoption>
<auro-menuoption value="Indianapolis, IN (IND-Indianapolis Intl.)" id="Indianapolis, IN (IND-Indianapolis Intl.)" suggest="Indianapolis, IN (IND-Indianapolis Intl.)">Indianapolis, IN (IND-Indianapolis Intl.)</auro-menuoption>
<auro-menuoption value="International Falls, MN (INL-Falls Intl.)" id="International Falls, MN (INL-Falls Intl.)" suggest="International Falls, MN (INL-Falls Intl.)">International Falls, MN (INL-Falls Intl.)</auro-menuoption>
<auro-menuoption value="Iron Mountain, MI (IMT-Iron Mountain)" id="Iron Mountain, MI (IMT-Iron Mountain)" suggest="Iron Mountain, MI (IMT-Iron Mountain)">Iron Mountain, MI (IMT-Iron Mountain)</auro-menuoption>
<auro-menuoption value="Islip, NY (ISP-MacArthur)" id="Islip, NY (ISP-MacArthur)" suggest="Islip, NY (ISP-MacArthur)">Islip, NY (ISP-MacArthur)</auro-menuoption>
<auro-menuoption value="Ithaca, NY (ITH-Ithaca)" id="Ithaca, NY (ITH-Ithaca)" suggest="Ithaca, NY (ITH-Ithaca)">Ithaca, NY (ITH-Ithaca)</auro-menuoption>
<auro-menuoption value="Ixtapa, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)" id="Ixtapa, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)" suggest="Ixtapa, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)">Ixtapa, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)</auro-menuoption>
<auro-menuoption value="Jackson Hole, WY (JAC-Jackson Hole)" id="Jackson Hole, WY (JAC-Jackson Hole)" suggest="Jackson Hole, WY (JAC-Jackson Hole)">Jackson Hole, WY (JAC-Jackson Hole)</auro-menuoption>
<auro-menuoption value="Jackson, MS (JAN-Jackson Intl.)" id="Jackson, MS (JAN-Jackson Intl.)" suggest="Jackson, MS (JAN-Jackson Intl.)">Jackson, MS (JAN-Jackson Intl.)</auro-menuoption>
<auro-menuoption value="Jacksonville, FL (JAX-Jacksonville Intl.)" id="Jacksonville, FL (JAX-Jacksonville Intl.)" suggest="Jacksonville, FL (JAX-Jacksonville Intl.)">Jacksonville, FL (JAX-Jacksonville Intl.)</auro-menuoption>
<auro-menuoption value="Jacksonville, NC (OAJ-Jacksonville)" id="Jacksonville, NC (OAJ-Jacksonville)" suggest="Jacksonville, NC (OAJ-Jacksonville)">Jacksonville, NC (OAJ-Jacksonville)</auro-menuoption>
<auro-menuoption value="Juneau, AK (JNU-Juneau Intl.)" id="Juneau, AK (JNU-Juneau Intl.)" suggest="Juneau, AK (JNU-Juneau Intl.)">Juneau, AK (JNU-Juneau Intl.)</auro-menuoption>
<auro-menuoption value="Kahului, HI (OGG-Kahului/Maui)" id="Kahului, HI (OGG-Kahului/Maui)" suggest="Kahului, HI (OGG-Kahului/Maui)">Kahului, HI (OGG-Kahului/Maui)</auro-menuoption>
<auro-menuoption value="Kailua, HI (KOA-Keahole)" id="Kailua, HI (KOA-Keahole)" suggest="Kailua, HI (KOA-Keahole)">Kailua, HI (KOA-Keahole)</auro-menuoption>
<auro-menuoption value="Kalamazoo, MI (AZO-Kalamazoo/Battle Creek Intl.)" id="Kalamazoo, MI (AZO-Kalamazoo/Battle Creek Intl.)" suggest="Kalamazoo, MI (AZO-Kalamazoo/Battle Creek Intl.)">Kalamazoo, MI (AZO-Kalamazoo/Battle Creek Intl.)</auro-menuoption>
<auro-menuoption value="Kalispell, MT (FCA-Glacier Park Intl.)" id="Kalispell, MT (FCA-Glacier Park Intl.)" suggest="Kalispell, MT (FCA-Glacier Park Intl.)">Kalispell, MT (FCA-Glacier Park Intl.)</auro-menuoption>
<auro-menuoption value="Kansas City, MO (MCI-Kansas City Intl.)" id="Kansas City, MO (MCI-Kansas City Intl.)" suggest="Kansas City, MO (MCI-Kansas City Intl.)">Kansas City, MO (MCI-Kansas City Intl.)</auro-menuoption>
<auro-menuoption value="Kelowna, BC, Canada (YLW-Ellison Field)" id="Kelowna, BC, Canada (YLW-Ellison Field)" suggest="Kelowna, BC, Canada (YLW-Ellison Field)">Kelowna, BC, Canada (YLW-Ellison Field)</auro-menuoption>
<auro-menuoption value="Kenai, AK (ENA-Kenai)" id="Kenai, AK (ENA-Kenai)" suggest="Kenai, AK (ENA-Kenai)">Kenai, AK (ENA-Kenai)</auro-menuoption>
<auro-menuoption value="Kennewick, WA (PSC-Tri-Cities)" id="Kennewick, WA (PSC-Tri-Cities)" suggest="Kennewick, WA (PSC-Tri-Cities)">Kennewick, WA (PSC-Tri-Cities)</auro-menuoption>
<auro-menuoption value="Ketchikan, AK (KTN-Ketchikan Intl.)" id="Ketchikan, AK (KTN-Ketchikan Intl.)" suggest="Ketchikan, AK (KTN-Ketchikan Intl.)">Ketchikan, AK (KTN-Ketchikan Intl.)</auro-menuoption>
<auro-menuoption value="Key West, FL (EYW-Key West Intl.)" id="Key West, FL (EYW-Key West Intl.)" suggest="Key West, FL (EYW-Key West Intl.)">Key West, FL (EYW-Key West Intl.)</auro-menuoption>
<auro-menuoption value="Killeen, TX (GRK-Killeen Gray AAF)" id="Killeen, TX (GRK-Killeen Gray AAF)" suggest="Killeen, TX (GRK-Killeen Gray AAF)">Killeen, TX (GRK-Killeen Gray AAF)</auro-menuoption>
<auro-menuoption value="King Salmon, AK (AKN-King Salmon)" id="King Salmon, AK (AKN-King Salmon)" suggest="King Salmon, AK (AKN-King Salmon)">King Salmon, AK (AKN-King Salmon)</auro-menuoption>
<auro-menuoption value="Knoxville, TN (TYS-McGhee/Tyson)" id="Knoxville, TN (TYS-McGhee/Tyson)" suggest="Knoxville, TN (TYS-McGhee/Tyson)">Knoxville, TN (TYS-McGhee/Tyson)</auro-menuoption>
<auro-menuoption value="Kodiak, AK (ADQ-Kodiak)" id="Kodiak, AK (ADQ-Kodiak)" suggest="Kodiak, AK (ADQ-Kodiak)">Kodiak, AK (ADQ-Kodiak)</auro-menuoption>
<auro-menuoption value="Kona, HI (KOA-Keahole)" id="Kona, HI (KOA-Keahole)" suggest="Kona, HI (KOA-Keahole)">Kona, HI (KOA-Keahole)</auro-menuoption>
<auro-menuoption value="Kotzebue, AK (OTZ-Ralph Wien Memorial)" id="Kotzebue, AK (OTZ-Ralph Wien Memorial)" suggest="Kotzebue, AK (OTZ-Ralph Wien Memorial)">Kotzebue, AK (OTZ-Ralph Wien Memorial)</auro-menuoption>
<auro-menuoption value="La Crosse, WI (LSE-La Crosse Municipal)" id="La Crosse, WI (LSE-La Crosse Municipal)" suggest="La Crosse, WI (LSE-La Crosse Municipal)">La Crosse, WI (LSE-La Crosse Municipal)</auro-menuoption>
<auro-menuoption value="La Paz, Mexico (LAP-La Paz)" id="La Paz, Mexico (LAP-La Paz)" suggest="La Paz, Mexico (LAP-La Paz)">La Paz, Mexico (LAP-La Paz)</auro-menuoption>
<auro-menuoption value="Lafayette, LA (LFT-Lafayette Regional)" id="Lafayette, LA (LFT-Lafayette Regional)" suggest="Lafayette, LA (LFT-Lafayette Regional)">Lafayette, LA (LFT-Lafayette Regional)</auro-menuoption>
<auro-menuoption value="Lake Charles, LA (LCH-Lake Charles Regional)" id="Lake Charles, LA (LCH-Lake Charles Regional)" suggest="Lake Charles, LA (LCH-Lake Charles Regional)">Lake Charles, LA (LCH-Lake Charles Regional)</auro-menuoption>
<auro-menuoption value="Lansing, MI (LAN-Capital City)" id="Lansing, MI (LAN-Capital City)" suggest="Lansing, MI (LAN-Capital City)">Lansing, MI (LAN-Capital City)</auro-menuoption>
<auro-menuoption value="Laredo, TX (LRD-Laredo Intl.)" id="Laredo, TX (LRD-Laredo Intl.)" suggest="Laredo, TX (LRD-Laredo Intl.)">Laredo, TX (LRD-Laredo Intl.)</auro-menuoption>
<auro-menuoption value="Las Vegas, NV (LAS-Harry Reid Intl.)" id="Las Vegas, NV (LAS-Harry Reid Intl.)" suggest="Las Vegas, NV (LAS-Harry Reid Intl.)">Las Vegas, NV (LAS-Harry Reid Intl.)</auro-menuoption>
<auro-menuoption value="Lawton, OK (LAW-Lawton Municipal)" id="Lawton, OK (LAW-Lawton Municipal)" suggest="Lawton, OK (LAW-Lawton Municipal)">Lawton, OK (LAW-Lawton Municipal)</auro-menuoption>
<auro-menuoption value="Leon, Mexico (BJX-Del Bajio)" id="Leon, Mexico (BJX-Del Bajio)" suggest="Leon, Mexico (BJX-Del Bajio)">Leon, Mexico (BJX-Del Bajio)</auro-menuoption>
<auro-menuoption value="Lewiston, ID (LWS-Nez Perce County Regional)" id="Lewiston, ID (LWS-Nez Perce County Regional)" suggest="Lewiston, ID (LWS-Nez Perce County Regional)">Lewiston, ID (LWS-Nez Perce County Regional)</auro-menuoption>
<auro-menuoption value="Lexington, KY (LEX-Blue Grass Field)" id="Lexington, KY (LEX-Blue Grass Field)" suggest="Lexington, KY (LEX-Blue Grass Field)">Lexington, KY (LEX-Blue Grass Field)</auro-menuoption>
<auro-menuoption value="Liberia, Costa Rica (LIR-Guanacaste)" id="Liberia, Costa Rica (LIR-Guanacaste)" suggest="Liberia, Costa Rica (LIR-Guanacaste)">Liberia, Costa Rica (LIR-Guanacaste)</auro-menuoption>
<auro-menuoption value="Lihue, HI (LIH-Lihue/Kauai)" id="Lihue, HI (LIH-Lihue/Kauai)" suggest="Lihue, HI (LIH-Lihue/Kauai)">Lihue, HI (LIH-Lihue/Kauai)</auro-menuoption>
<auro-menuoption value="Little Rock, AR (LIT-Adams Field)" id="Little Rock, AR (LIT-Adams Field)" suggest="Little Rock, AR (LIT-Adams Field)">Little Rock, AR (LIT-Adams Field)</auro-menuoption>
<auro-menuoption value="Long Beach, CA (LGB-Long Beach Municipal)" id="Long Beach, CA (LGB-Long Beach Municipal)" suggest="Long Beach, CA (LGB-Long Beach Municipal)">Long Beach, CA (LGB-Long Beach Municipal)</auro-menuoption>
<auro-menuoption value="Longview, TX (GGG-Gregg County)" id="Longview, TX (GGG-Gregg County)" suggest="Longview, TX (GGG-Gregg County)">Longview, TX (GGG-Gregg County)</auro-menuoption>
<auro-menuoption value="Loreto, Mexico (LTO-Loreto)" id="Loreto, Mexico (LTO-Loreto)" suggest="Loreto, Mexico (LTO-Loreto)">Loreto, Mexico (LTO-Loreto)</auro-menuoption>
<auro-menuoption value="Los Angeles, CA (QLA-All Airports)" id="Los Angeles, CA (QLA-All Airports)" suggest="Los Angeles, CA (QLA-All Airports)">Los Angeles, CA (QLA-All Airports)</auro-menuoption>
<auro-menuoption value="Los Angeles, CA (BUR-Burbank/Glendale/Pasadena)" id="Los Angeles, CA (BUR-Burbank/Glendale/Pasadena)" suggest="Los Angeles, CA (BUR-Burbank/Glendale/Pasadena)">Los Angeles, CA (BUR-Burbank/Glendale/Pasadena)</auro-menuoption>
<auro-menuoption value="Los Angeles, CA (LAX-Los Angeles Intl.)" id="Los Angeles, CA (LAX-Los Angeles Intl.)" suggest="Los Angeles, CA (LAX-Los Angeles Intl.)">Los Angeles, CA (LAX-Los Angeles Intl.)</auro-menuoption>
<auro-menuoption value="Los Angeles, CA (LGB-Long Beach Municipal)" id="Los Angeles, CA (LGB-Long Beach Municipal)" suggest="Los Angeles, CA (LGB-Long Beach Municipal)">Los Angeles, CA (LGB-Long Beach Municipal)</auro-menuoption>
<auro-menuoption value="Los Angeles, CA (ONT-Ontario Intl.)" id="Los Angeles, CA (ONT-Ontario Intl.)" suggest="Los Angeles, CA (ONT-Ontario Intl.)">Los Angeles, CA (ONT-Ontario Intl.)</auro-menuoption>
<auro-menuoption value="Los Angeles, CA (SNA-Santa Ana)" id="Los Angeles, CA (SNA-Santa Ana)" suggest="Los Angeles, CA (SNA-Santa Ana)">Los Angeles, CA (SNA-Santa Ana)</auro-menuoption>
<auro-menuoption value="Los Cabos, Mexico (SJD-Los Cabos Intl.)" id="Los Cabos, Mexico (SJD-Los Cabos Intl.)" suggest="Los Cabos, Mexico (SJD-Los Cabos Intl.)">Los Cabos, Mexico (SJD-Los Cabos Intl.)</auro-menuoption>
<auro-menuoption value="Louisville, KY (SDF-Standiford Field)" id="Louisville, KY (SDF-Standiford Field)" suggest="Louisville, KY (SDF-Standiford Field)">Louisville, KY (SDF-Standiford Field)</auro-menuoption>
<auro-menuoption value="Lubbock, TX (LBB-Lubbock Intl.)" id="Lubbock, TX (LBB-Lubbock Intl.)" suggest="Lubbock, TX (LBB-Lubbock Intl.)">Lubbock, TX (LBB-Lubbock Intl.)</auro-menuoption>
<auro-menuoption value="Lynchburg, VA (LYH-Lynchburg)" id="Lynchburg, VA (LYH-Lynchburg)" suggest="Lynchburg, VA (LYH-Lynchburg)">Lynchburg, VA (LYH-Lynchburg)</auro-menuoption>
<auro-menuoption value="Madison, WI (MSN-Dane County Regional)" id="Madison, WI (MSN-Dane County Regional)" suggest="Madison, WI (MSN-Dane County Regional)">Madison, WI (MSN-Dane County Regional)</auro-menuoption>
<auro-menuoption value="Manchester, NH (MHT-Manchester)" id="Manchester, NH (MHT-Manchester)" suggest="Manchester, NH (MHT-Manchester)">Manchester, NH (MHT-Manchester)</auro-menuoption>
<auro-menuoption value="Manhattan, KS (MHK-Manhattan)" id="Manhattan, KS (MHK-Manhattan)" suggest="Manhattan, KS (MHK-Manhattan)">Manhattan, KS (MHK-Manhattan)</auro-menuoption>
<auro-menuoption value="Manzanillo, Mexico (ZLO-Manzanillo - Costa Alegre)" id="Manzanillo, Mexico (ZLO-Manzanillo - Costa Alegre)" suggest="Manzanillo, Mexico (ZLO-Manzanillo - Costa Alegre)">Manzanillo, Mexico (ZLO-Manzanillo - Costa Alegre)</auro-menuoption>
<auro-menuoption value="Marquette, MI (MQT-Marquette County)" id="Marquette, MI (MQT-Marquette County)" suggest="Marquette, MI (MQT-Marquette County)">Marquette, MI (MQT-Marquette County)</auro-menuoption>
<auro-menuoption value="Martha's Vineyard, MA (MVY-Martha's Vineyard)" id="Martha's Vineyard, MA (MVY-Martha's Vineyard)" suggest="Martha's Vineyard, MA (MVY-Martha's Vineyard)">Martha's Vineyard, MA (MVY-Martha's Vineyard)</auro-menuoption>
<auro-menuoption value="Maui, HI (OGG-Kahului/Maui)" id="Maui, HI (OGG-Kahului/Maui)" suggest="Maui, HI (OGG-Kahului/Maui)">Maui, HI (OGG-Kahului/Maui)</auro-menuoption>
<auro-menuoption value="Mazatlan, Mexico (MZT-Gen Rafael Buelna)" id="Mazatlan, Mexico (MZT-Gen Rafael Buelna)" suggest="Mazatlan, Mexico (MZT-Gen Rafael Buelna)">Mazatlan, Mexico (MZT-Gen Rafael Buelna)</auro-menuoption>
<auro-menuoption value="McAllen, TX (MFE-Miller Intl.)" id="McAllen, TX (MFE-Miller Intl.)" suggest="McAllen, TX (MFE-Miller Intl.)">McAllen, TX (MFE-Miller Intl.)</auro-menuoption>
<auro-menuoption value="Medford, OR (MFR-Medford/Jackson County)" id="Medford, OR (MFR-Medford/Jackson County)" suggest="Medford, OR (MFR-Medford/Jackson County)">Medford, OR (MFR-Medford/Jackson County)</auro-menuoption>
<auro-menuoption value="Melbourne, FL (MLB-Melbourne Intl.)" id="Melbourne, FL (MLB-Melbourne Intl.)" suggest="Melbourne, FL (MLB-Melbourne Intl.)">Melbourne, FL (MLB-Melbourne Intl.)</auro-menuoption>
<auro-menuoption value="Memphis, TN (MEM-Memphis Intl.)" id="Memphis, TN (MEM-Memphis Intl.)" suggest="Memphis, TN (MEM-Memphis Intl.)">Memphis, TN (MEM-Memphis Intl.)</auro-menuoption>
<auro-menuoption value="Merida, Mexico (MID-Manuel Crescencio Rejon)" id="Merida, Mexico (MID-Manuel Crescencio Rejon)" suggest="Merida, Mexico (MID-Manuel Crescencio Rejon)">Merida, Mexico (MID-Manuel Crescencio Rejon)</auro-menuoption>
<auro-menuoption value="Mexico City, Mexico (MEX-Juarez Intl.)" id="Mexico City, Mexico (MEX-Juarez Intl.)" suggest="Mexico City, Mexico (MEX-Juarez Intl.)">Mexico City, Mexico (MEX-Juarez Intl.)</auro-menuoption>
<auro-menuoption value="Miami, FL (QMI-All Airports)" id="Miami, FL (QMI-All Airports)" suggest="Miami, FL (QMI-All Airports)">Miami, FL (QMI-All Airports)</auro-menuoption>
<auro-menuoption value="Miami, FL (FLL-Hollywood Intl.)" id="Miami, FL (FLL-Hollywood Intl.)" suggest="Miami, FL (FLL-Hollywood Intl.)">Miami, FL (FLL-Hollywood Intl.)</auro-menuoption>
<auro-menuoption value="Miami, FL (MIA-Miami Intl.)" id="Miami, FL (MIA-Miami Intl.)" suggest="Miami, FL (MIA-Miami Intl.)">Miami, FL (MIA-Miami Intl.)</auro-menuoption>
<auro-menuoption value="Miami, FL (PBI-Palm Beach Intl.)" id="Miami, FL (PBI-Palm Beach Intl.)" suggest="Miami, FL (PBI-Palm Beach Intl.)">Miami, FL (PBI-Palm Beach Intl.)</auro-menuoption>
<auro-menuoption value="Midland, TX (MAF-Midland Intl.)" id="Midland, TX (MAF-Midland Intl.)" suggest="Midland, TX (MAF-Midland Intl.)">Midland, TX (MAF-Midland Intl.)</auro-menuoption>
<auro-menuoption value="Milwaukee, WI (MKE-Milwaukee Mitchell International Airport)" id="Milwaukee, WI (MKE-Milwaukee Mitchell International Airport)" suggest="Milwaukee, WI (MKE-Milwaukee Mitchell International Airport)">Milwaukee, WI (MKE-Milwaukee Mitchell International Airport)</auro-menuoption>
<auro-menuoption value="Minneapolis, MN (MSP-Minneapolis/St. Paul Intl.)" id="Minneapolis, MN (MSP-Minneapolis/St. Paul Intl.)" suggest="Minneapolis, MN (MSP-Minneapolis/St. Paul Intl.)">Minneapolis, MN (MSP-Minneapolis/St. Paul Intl.)</auro-menuoption>
<auro-menuoption value="Minot, ND (MOT-Minot Intl.)" id="Minot, ND (MOT-Minot Intl.)" suggest="Minot, ND (MOT-Minot Intl.)">Minot, ND (MOT-Minot Intl.)</auro-menuoption>
<auro-menuoption value="Missoula, MT (MSO-Missoula County)" id="Missoula, MT (MSO-Missoula County)" suggest="Missoula, MT (MSO-Missoula County)">Missoula, MT (MSO-Missoula County)</auro-menuoption>
<auro-menuoption value="Moab, UT (CNY-Moab)" id="Moab, UT (CNY-Moab)" suggest="Moab, UT (CNY-Moab)">Moab, UT (CNY-Moab)</auro-menuoption>
<auro-menuoption value="Mobile, AL (MOB-Mobile Regional)" id="Mobile, AL (MOB-Mobile Regional)" suggest="Mobile, AL (MOB-Mobile Regional)">Mobile, AL (MOB-Mobile Regional)</auro-menuoption>
<auro-menuoption value="Moline, IL (MLI-Quad City)" id="Moline, IL (MLI-Quad City)" suggest="Moline, IL (MLI-Quad City)">Moline, IL (MLI-Quad City)</auro-menuoption>
<auro-menuoption value="Monroe, LA (MLU-Monroe Regional)" id="Monroe, LA (MLU-Monroe Regional)" suggest="Monroe, LA (MLU-Monroe Regional)">Monroe, LA (MLU-Monroe Regional)</auro-menuoption>
<auro-menuoption value="Monterey/Carmel, CA (MRY-Monterey Peninsula)" id="Monterey/Carmel, CA (MRY-Monterey Peninsula)" suggest="Monterey/Carmel, CA (MRY-Monterey Peninsula)">Monterey/Carmel, CA (MRY-Monterey Peninsula)</auro-menuoption>
<auro-menuoption value="Monterrey, Mexico (MTY-Gen Mariano Escobedo)" id="Monterrey, Mexico (MTY-Gen Mariano Escobedo)" suggest="Monterrey, Mexico (MTY-Gen Mariano Escobedo)">Monterrey, Mexico (MTY-Gen Mariano Escobedo)</auro-menuoption>
<auro-menuoption value="Montgomery, AL (MGM-Dannelly Field)" id="Montgomery, AL (MGM-Dannelly Field)" suggest="Montgomery, AL (MGM-Dannelly Field)">Montgomery, AL (MGM-Dannelly Field)</auro-menuoption>
<auro-menuoption value="Montreal, QC, Canada (YUL-Dorval)" id="Montreal, QC, Canada (YUL-Dorval)" suggest="Montreal, QC, Canada (YUL-Dorval)">Montreal, QC, Canada (YUL-Dorval)</auro-menuoption>
<auro-menuoption value="Montrose, CO (MTJ-County)" id="Montrose, CO (MTJ-County)" suggest="Montrose, CO (MTJ-County)">Montrose, CO (MTJ-County)</auro-menuoption>
<auro-menuoption value="Morelia, Mexico (MLM-Morelia)" id="Morelia, Mexico (MLM-Morelia)" suggest="Morelia, Mexico (MLM-Morelia)">Morelia, Mexico (MLM-Morelia)</auro-menuoption>
<auro-menuoption value="Moscow, ID (PUW-Pullman/Moscow Regional)" id="Moscow, ID (PUW-Pullman/Moscow Regional)" suggest="Moscow, ID (PUW-Pullman/Moscow Regional)">Moscow, ID (PUW-Pullman/Moscow Regional)</auro-menuoption>
<auro-menuoption value="Myrtle Beach, SC (MYR-Myrtle Beach Jetport)" id="Myrtle Beach, SC (MYR-Myrtle Beach Jetport)" suggest="Myrtle Beach, SC (MYR-Myrtle Beach Jetport)">Myrtle Beach, SC (MYR-Myrtle Beach Jetport)</auro-menuoption>
<auro-menuoption value="Nantucket, MA (ACK-Nantucket)" id="Nantucket, MA (ACK-Nantucket)" suggest="Nantucket, MA (ACK-Nantucket)">Nantucket, MA (ACK-Nantucket)</auro-menuoption>
<auro-menuoption value="Nashville, TN (BNA-Nashville Intl.)" id="Nashville, TN (BNA-Nashville Intl.)" suggest="Nashville, TN (BNA-Nashville Intl.)">Nashville, TN (BNA-Nashville Intl.)</auro-menuoption>
<auro-menuoption value="New Bern, NC (EWN-New Bern)" id="New Bern, NC (EWN-New Bern)" suggest="New Bern, NC (EWN-New Bern)">New Bern, NC (EWN-New Bern)</auro-menuoption>
<auro-menuoption value="New Orleans, LA (MSY-New Orleans Intl.)" id="New Orleans, LA (MSY-New Orleans Intl.)" suggest="New Orleans, LA (MSY-New Orleans Intl.)">New Orleans, LA (MSY-New Orleans Intl.)</auro-menuoption>
<auro-menuoption value="New York, NY (NYC-All Airports)" id="New York, NY (NYC-All Airports)" suggest="New York, NY (NYC-All Airports)">New York, NY (NYC-All Airports)</auro-menuoption>
<auro-menuoption value="New York, NY (EWR-Liberty Intl.)" id="New York, NY (EWR-Liberty Intl.)" suggest="New York, NY (EWR-Liberty Intl.)">New York, NY (EWR-Liberty Intl.)</auro-menuoption>
<auro-menuoption value="New York, NY (JFK-Kennedy)" id="New York, NY (JFK-Kennedy)" suggest="New York, NY (JFK-Kennedy)">New York, NY (JFK-Kennedy)</auro-menuoption>
<auro-menuoption value="New York, NY (LGA-LaGuardia)" id="New York, NY (LGA-LaGuardia)" suggest="New York, NY (LGA-LaGuardia)">New York, NY (LGA-LaGuardia)</auro-menuoption>
<auro-menuoption value="Newark, NJ (EWR-Liberty Intl.)" id="Newark, NJ (EWR-Liberty Intl.)" suggest="Newark, NJ (EWR-Liberty Intl.)">Newark, NJ (EWR-Liberty Intl.)</auro-menuoption>
<auro-menuoption value="Newport News, VA (PHF-Newport News)" id="Newport News, VA (PHF-Newport News)" suggest="Newport News, VA (PHF-Newport News)">Newport News, VA (PHF-Newport News)</auro-menuoption>
<auro-menuoption value="Nome, AK (OME-Nome)" id="Nome, AK (OME-Nome)" suggest="Nome, AK (OME-Nome)">Nome, AK (OME-Nome)</auro-menuoption>
<auro-menuoption value="Norfolk, VA (ORF-Norfolk Intl.)" id="Norfolk, VA (ORF-Norfolk Intl.)" suggest="Norfolk, VA (ORF-Norfolk Intl.)">Norfolk, VA (ORF-Norfolk Intl.)</auro-menuoption>
<auro-menuoption value="Oakland, CA (OAK-Oakland Intl.)" id="Oakland, CA (OAK-Oakland Intl.)" suggest="Oakland, CA (OAK-Oakland Intl.)">Oakland, CA (OAK-Oakland Intl.)</auro-menuoption>
<auro-menuoption value="Oaxaca, Mexico (OAX-Oaxaca)" id="Oaxaca, Mexico (OAX-Oaxaca)" suggest="Oaxaca, Mexico (OAX-Oaxaca)">Oaxaca, Mexico (OAX-Oaxaca)</auro-menuoption>
<auro-menuoption value="Oklahoma City, OK (OKC-Will Rogers World)" id="Oklahoma City, OK (OKC-Will Rogers World)" suggest="Oklahoma City, OK (OKC-Will Rogers World)">Oklahoma City, OK (OKC-Will Rogers World)</auro-menuoption>
<auro-menuoption value="Omaha, NE (OMA-Eppley Field)" id="Omaha, NE (OMA-Eppley Field)" suggest="Omaha, NE (OMA-Eppley Field)">Omaha, NE (OMA-Eppley Field)</auro-menuoption>
<auro-menuoption value="Ontario, CA (ONT-Ontario Intl.)" id="Ontario, CA (ONT-Ontario Intl.)" suggest="Ontario, CA (ONT-Ontario Intl.)">Ontario, CA (ONT-Ontario Intl.)</auro-menuoption>
<auro-menuoption value="Orange County, CA (SNA-Santa Ana)" id="Orange County, CA (SNA-Santa Ana)" suggest="Orange County, CA (SNA-Santa Ana)">Orange County, CA (SNA-Santa Ana)</auro-menuoption>
<auro-menuoption value="Orlando, FL (MCO-Orlando Intl.)" id="Orlando, FL (MCO-Orlando Intl.)" suggest="Orlando, FL (MCO-Orlando Intl.)">Orlando, FL (MCO-Orlando Intl.)</auro-menuoption>
<auro-menuoption value="Palm Springs, CA (PSP-Palm Springs International Airport)" id="Palm Springs, CA (PSP-Palm Springs International Airport)" suggest="Palm Springs, CA (PSP-Palm Springs International Airport)">Palm Springs, CA (PSP-Palm Springs International Airport)</auro-menuoption>
<auro-menuoption value="Panama City, FL (ECP-Bay County)" id="Panama City, FL (ECP-Bay County)" suggest="Panama City, FL (ECP-Bay County)">Panama City, FL (ECP-Bay County)</auro-menuoption>
<auro-menuoption value="Pasco, WA (PSC-Tri-Cities)" id="Pasco, WA (PSC-Tri-Cities)" suggest="Pasco, WA (PSC-Tri-Cities)">Pasco, WA (PSC-Tri-Cities)</auro-menuoption>
<auro-menuoption value="Pellston, MI (PLN-Emmet County/Mackinac Isl.)" id="Pellston, MI (PLN-Emmet County/Mackinac Isl.)" suggest="Pellston, MI (PLN-Emmet County/Mackinac Isl.)">Pellston, MI (PLN-Emmet County/Mackinac Isl.)</auro-menuoption>
<auro-menuoption value="Pensacola, FL (PNS-Pensacola Regional)" id="Pensacola, FL (PNS-Pensacola Regional)" suggest="Pensacola, FL (PNS-Pensacola Regional)">Pensacola, FL (PNS-Pensacola Regional)</auro-menuoption>
<auro-menuoption value="Peoria, IL (PIA-Greater Peoria)" id="Peoria, IL (PIA-Greater Peoria)" suggest="Peoria, IL (PIA-Greater Peoria)">Peoria, IL (PIA-Greater Peoria)</auro-menuoption>
<auro-menuoption value="Petersburg, AK (PSG-James A. Johnson)" id="Petersburg, AK (PSG-James A. Johnson)" suggest="Petersburg, AK (PSG-James A. Johnson)">Petersburg, AK (PSG-James A. Johnson)</auro-menuoption>
<auro-menuoption value="Philadelphia, PA (PHL-Philadelphia Intl.)" id="Philadelphia, PA (PHL-Philadelphia Intl.)" suggest="Philadelphia, PA (PHL-Philadelphia Intl.)">Philadelphia, PA (PHL-Philadelphia Intl.)</auro-menuoption>
<auro-menuoption value="Phoenix, AZ (PHX-Sky Harbor Intl.)" id="Phoenix, AZ (PHX-Sky Harbor Intl.)" suggest="Phoenix, AZ (PHX-Sky Harbor Intl.)">Phoenix, AZ (PHX-Sky Harbor Intl.)</auro-menuoption>
<auro-menuoption value="Pittsburgh, PA (PIT-Greater Pittsburgh Intl.)" id="Pittsburgh, PA (PIT-Greater Pittsburgh Intl.)" suggest="Pittsburgh, PA (PIT-Greater Pittsburgh Intl.)">Pittsburgh, PA (PIT-Greater Pittsburgh Intl.)</auro-menuoption>
<auro-menuoption value="Pocatello, ID (PIH-Pocatello Regional)" id="Pocatello, ID (PIH-Pocatello Regional)" suggest="Pocatello, ID (PIH-Pocatello Regional)">Pocatello, ID (PIH-Pocatello Regional)</auro-menuoption>
<auro-menuoption value="Portland, ME (PWM-Intl. Jet Port)" id="Portland, ME (PWM-Intl. Jet Port)" suggest="Portland, ME (PWM-Intl. Jet Port)">Portland, ME (PWM-Intl. Jet Port)</auro-menuoption>
<auro-menuoption value="Portland, OR (PDX-Portland Intl.)" id="Portland, OR (PDX-Portland Intl.)" suggest="Portland, OR (PDX-Portland Intl.)">Portland, OR (PDX-Portland Intl.)</auro-menuoption>
<auro-menuoption value="Providence, RI (PVD-T.F. Green State)" id="Providence, RI (PVD-T.F. Green State)" suggest="Providence, RI (PVD-T.F. Green State)">Providence, RI (PVD-T.F. Green State)</auro-menuoption>
<auro-menuoption value="Prudhoe Bay, AK (SCC-Deadhorse)" id="Prudhoe Bay, AK (SCC-Deadhorse)" suggest="Prudhoe Bay, AK (SCC-Deadhorse)">Prudhoe Bay, AK (SCC-Deadhorse)</auro-menuoption>
<auro-menuoption value="Puerto Vallarta, Mexico (PVR-Gustavo Diaz Ordaz)" id="Puerto Vallarta, Mexico (PVR-Gustavo Diaz Ordaz)" suggest="Puerto Vallarta, Mexico (PVR-Gustavo Diaz Ordaz)">Puerto Vallarta, Mexico (PVR-Gustavo Diaz Ordaz)</auro-menuoption>
<auro-menuoption value="Pullman, WA (PUW-Pullman/Moscow Regional)" id="Pullman, WA (PUW-Pullman/Moscow Regional)" suggest="Pullman, WA (PUW-Pullman/Moscow Regional)">Pullman, WA (PUW-Pullman/Moscow Regional)</auro-menuoption>
<auro-menuoption value="Quebec, QC, Canada (YQB-Quebec)" id="Quebec, QC, Canada (YQB-Quebec)" suggest="Quebec, QC, Canada (YQB-Quebec)">Quebec, QC, Canada (YQB-Quebec)</auro-menuoption>
<auro-menuoption value="Queretaro, Mexico (QRO-Queretaro)" id="Queretaro, Mexico (QRO-Queretaro)" suggest="Queretaro, Mexico (QRO-Queretaro)">Queretaro, Mexico (QRO-Queretaro)</auro-menuoption>
<auro-menuoption value="Raleigh, NC (RDU-Raleigh Durham Intl.)" id="Raleigh, NC (RDU-Raleigh Durham Intl.)" suggest="Raleigh, NC (RDU-Raleigh Durham Intl.)">Raleigh, NC (RDU-Raleigh Durham Intl.)</auro-menuoption>
<auro-menuoption value="Rapid City, SD (RAP-Rapid City Regional)" id="Rapid City, SD (RAP-Rapid City Regional)" suggest="Rapid City, SD (RAP-Rapid City Regional)">Rapid City, SD (RAP-Rapid City Regional)</auro-menuoption>
<auro-menuoption value="Redding, CA (RDD-Redding Municipal)" id="Redding, CA (RDD-Redding Municipal)" suggest="Redding, CA (RDD-Redding Municipal)">Redding, CA (RDD-Redding Municipal)</auro-menuoption>
<auro-menuoption value="Redmond, OR (RDM-Redmond/Bend/Roberts Field)" id="Redmond, OR (RDM-Redmond/Bend/Roberts Field)" suggest="Redmond, OR (RDM-Redmond/Bend/Roberts Field)">Redmond, OR (RDM-Redmond/Bend/Roberts Field)</auro-menuoption>
<auro-menuoption value="Reno, NV (RNO-Reno/Tahoe Intl.)" id="Reno, NV (RNO-Reno/Tahoe Intl.)" suggest="Reno, NV (RNO-Reno/Tahoe Intl.)">Reno, NV (RNO-Reno/Tahoe Intl.)</auro-menuoption>
<auro-menuoption value="Rhinelander, WI (RHI-Oneida County)" id="Rhinelander, WI (RHI-Oneida County)" suggest="Rhinelander, WI (RHI-Oneida County)">Rhinelander, WI (RHI-Oneida County)</auro-menuoption>
<auro-menuoption value="Richmond, VA (RIC-Richmond Intl.)" id="Richmond, VA (RIC-Richmond Intl.)" suggest="Richmond, VA (RIC-Richmond Intl.)">Richmond, VA (RIC-Richmond Intl.)</auro-menuoption>
<auro-menuoption value="Riviera Nayarit, Mexico (PVR-Gustavo Diaz Ordaz)" id="Riviera Nayarit, Mexico (PVR-Gustavo Diaz Ordaz)" suggest="Riviera Nayarit, Mexico (PVR-Gustavo Diaz Ordaz)">Riviera Nayarit, Mexico (PVR-Gustavo Diaz Ordaz)</auro-menuoption>
<auro-menuoption value="Roanoke, VA (ROA-Roanoke Regional)" id="Roanoke, VA (ROA-Roanoke Regional)" suggest="Roanoke, VA (ROA-Roanoke Regional)">Roanoke, VA (ROA-Roanoke Regional)</auro-menuoption>
<auro-menuoption value="Rochester, MN (RST-Rochester Intl.)" id="Rochester, MN (RST-Rochester Intl.)" suggest="Rochester, MN (RST-Rochester Intl.)">Rochester, MN (RST-Rochester Intl.)</auro-menuoption>
<auro-menuoption value="Rochester, NY (ROC-Greater Rochester Intl.)" id="Rochester, NY (ROC-Greater Rochester Intl.)" suggest="Rochester, NY (ROC-Greater Rochester Intl.)">Rochester, NY (ROC-Greater Rochester Intl.)</auro-menuoption>
<auro-menuoption value="Roswell, NM (ROW-Roswell)" id="Roswell, NM (ROW-Roswell)" suggest="Roswell, NM (ROW-Roswell)">Roswell, NM (ROW-Roswell)</auro-menuoption>
<auro-menuoption value="Sacramento, CA (SMF-Sacramento Intl.)" id="Sacramento, CA (SMF-Sacramento Intl.)" suggest="Sacramento, CA (SMF-Sacramento Intl.)">Sacramento, CA (SMF-Sacramento Intl.)</auro-menuoption>
<auro-menuoption value="Saginaw, MI (MBS-Tri-City)" id="Saginaw, MI (MBS-Tri-City)" suggest="Saginaw, MI (MBS-Tri-City)">Saginaw, MI (MBS-Tri-City)</auro-menuoption>
<auro-menuoption value="Salisbury-Ocean City, MD (SBY-Salisbury-Ocean City)" id="Salisbury-Ocean City, MD (SBY-Salisbury-Ocean City)" suggest="Salisbury-Ocean City, MD (SBY-Salisbury-Ocean City)">Salisbury-Ocean City, MD (SBY-Salisbury-Ocean City)</auro-menuoption>
<auro-menuoption value="Salt Lake City, UT (SLC-Salt Lake City Intl.)" id="Salt Lake City, UT (SLC-Salt Lake City Intl.)" suggest="Salt Lake City, UT (SLC-Salt Lake City Intl.)">Salt Lake City, UT (SLC-Salt Lake City Intl.)</auro-menuoption>
<auro-menuoption value="San Angelo, TX (SJT-Mathis Field)" id="San Angelo, TX (SJT-Mathis Field)" suggest="San Angelo, TX (SJT-Mathis Field)">San Angelo, TX (SJT-Mathis Field)</auro-menuoption>
<auro-menuoption value="San Antonio, TX (SAT-San Antonio Intl.)" id="San Antonio, TX (SAT-San Antonio Intl.)" suggest="San Antonio, TX (SAT-San Antonio Intl.)">San Antonio, TX (SAT-San Antonio Intl.)</auro-menuoption>
<auro-menuoption value="San Diego, CA (SAN-San Diego International Airport)" id="San Diego, CA (SAN-San Diego International Airport)" suggest="San Diego, CA (SAN-San Diego International Airport)">San Diego, CA (SAN-San Diego International Airport)</auro-menuoption>
<auro-menuoption value="San Francisco, CA (SFO-San Francisco Intl.)" id="San Francisco, CA (SFO-San Francisco Intl.)" suggest="San Francisco, CA (SFO-San Francisco Intl.)">San Francisco, CA (SFO-San Francisco Intl.)</auro-menuoption>
<auro-menuoption value="San Jose del Cabo, Mexico (SJD-Los Cabos Intl.)" id="San Jose del Cabo, Mexico (SJD-Los Cabos Intl.)" suggest="San Jose del Cabo, Mexico (SJD-Los Cabos Intl.)">San Jose del Cabo, Mexico (SJD-Los Cabos Intl.)</auro-menuoption>
<auro-menuoption value="San Jose, CA (SJC-San Jose Intl.)" id="San Jose, CA (SJC-San Jose Intl.)" suggest="San Jose, CA (SJC-San Jose Intl.)">San Jose, CA (SJC-San Jose Intl.)</auro-menuoption>
<auro-menuoption value="San Jose, Costa Rica (SJO-San Jose Juan Santamaria)" id="San Jose, Costa Rica (SJO-San Jose Juan Santamaria)" suggest="San Jose, Costa Rica (SJO-San Jose Juan Santamaria)">San Jose, Costa Rica (SJO-San Jose Juan Santamaria)</auro-menuoption>
<auro-menuoption value="San Luis Obispo, CA (SBP-San Luis Obispo)" id="San Luis Obispo, CA (SBP-San Luis Obispo)" suggest="San Luis Obispo, CA (SBP-San Luis Obispo)">San Luis Obispo, CA (SBP-San Luis Obispo)</auro-menuoption>
<auro-menuoption value="San Luis Potosi, Mexico (SLP-San Luis Potosi)" id="San Luis Potosi, Mexico (SLP-San Luis Potosi)" suggest="San Luis Potosi, Mexico (SLP-San Luis Potosi)">San Luis Potosi, Mexico (SLP-San Luis Potosi)</auro-menuoption>
<auro-menuoption value="Sand Point, AK (SDP-Sand Point)" id="Sand Point, AK (SDP-Sand Point)" suggest="Sand Point, AK (SDP-Sand Point)">Sand Point, AK (SDP-Sand Point)</auro-menuoption>
<auro-menuoption value="Santa Ana, CA (SNA-Santa Ana)" id="Santa Ana, CA (SNA-Santa Ana)" suggest="Santa Ana, CA (SNA-Santa Ana)">Santa Ana, CA (SNA-Santa Ana)</auro-menuoption>
<auro-menuoption value="Santa Barbara, CA (SBA-Santa Barbara Municipal)" id="Santa Barbara, CA (SBA-Santa Barbara Municipal)" suggest="Santa Barbara, CA (SBA-Santa Barbara Municipal)">Santa Barbara, CA (SBA-Santa Barbara Municipal)</auro-menuoption>
<auro-menuoption value="Santa Fe, NM (SAF-Santa Fe)" id="Santa Fe, NM (SAF-Santa Fe)" suggest="Santa Fe, NM (SAF-Santa Fe)">Santa Fe, NM (SAF-Santa Fe)</auro-menuoption>
<auro-menuoption value="Santa Rosa, CA (STS-Santa Rosa)" id="Santa Rosa, CA (STS-Santa Rosa)" suggest="Santa Rosa, CA (STS-Santa Rosa)">Santa Rosa, CA (STS-Santa Rosa)</auro-menuoption>
<auro-menuoption value="Sarasota, FL (SRQ-Sarasota/Bradenton)" id="Sarasota, FL (SRQ-Sarasota/Bradenton)" suggest="Sarasota, FL (SRQ-Sarasota/Bradenton)">Sarasota, FL (SRQ-Sarasota/Bradenton)</auro-menuoption>
<auro-menuoption value="Sault Ste Marie, MI (CIU-Chippewa County Intl.)" id="Sault Ste Marie, MI (CIU-Chippewa County Intl.)" suggest="Sault Ste Marie, MI (CIU-Chippewa County Intl.)">Sault Ste Marie, MI (CIU-Chippewa County Intl.)</auro-menuoption>
<auro-menuoption value="Savannah, GA (SAV-Savannah Intl.)" id="Savannah, GA (SAV-Savannah Intl.)" suggest="Savannah, GA (SAV-Savannah Intl.)">Savannah, GA (SAV-Savannah Intl.)</auro-menuoption>
<auro-menuoption value="Seattle Area (All Airports)" id="Seattle Area (All Airports)" suggest="Seattle Area (All Airports)">Seattle Area (All Airports)</auro-menuoption>
<auro-menuoption value="Seattle Area (PAE-Paine Field)" id="Seattle Area (PAE-Paine Field)" suggest="Seattle Area (PAE-Paine Field)">Seattle Area (PAE-Paine Field)</auro-menuoption>
<auro-menuoption value="Seattle, WA (SEA-Seattle/Tacoma Intl.)" id="Seattle, WA (SEA-Seattle/Tacoma Intl.)" suggest="Seattle, WA (SEA-Seattle/Tacoma Intl.)">Seattle, WA (SEA-Seattle/Tacoma Intl.)</auro-menuoption>
<auro-menuoption value="Shreveport, LA (SHV-Shreveport Regional)" id="Shreveport, LA (SHV-Shreveport Regional)" suggest="Shreveport, LA (SHV-Shreveport Regional)">Shreveport, LA (SHV-Shreveport Regional)</auro-menuoption>
<auro-menuoption value="Sioux Falls, SD (FSD-Joe Foss Field)" id="Sioux Falls, SD (FSD-Joe Foss Field)" suggest="Sioux Falls, SD (FSD-Joe Foss Field)">Sioux Falls, SD (FSD-Joe Foss Field)</auro-menuoption>
<auro-menuoption value="Sitka, AK (SIT-Sitka)" id="Sitka, AK (SIT-Sitka)" suggest="Sitka, AK (SIT-Sitka)">Sitka, AK (SIT-Sitka)</auro-menuoption>
<auro-menuoption value="Sonoma County, CA (STS-Santa Rosa)" id="Sonoma County, CA (STS-Santa Rosa)" suggest="Sonoma County, CA (STS-Santa Rosa)">Sonoma County, CA (STS-Santa Rosa)</auro-menuoption>
<auro-menuoption value="South Bend, IN (SBN-Michiana Regional)" id="South Bend, IN (SBN-Michiana Regional)" suggest="South Bend, IN (SBN-Michiana Regional)">South Bend, IN (SBN-Michiana Regional)</auro-menuoption>
<auro-menuoption value="Spartanburg, SC (GSP-Spartanburg)" id="Spartanburg, SC (GSP-Spartanburg)" suggest="Spartanburg, SC (GSP-Spartanburg)">Spartanburg, SC (GSP-Spartanburg)</auro-menuoption>
<auro-menuoption value="Spokane, WA (GEG-Spokane Intl.)" id="Spokane, WA (GEG-Spokane Intl.)" suggest="Spokane, WA (GEG-Spokane Intl.)">Spokane, WA (GEG-Spokane Intl.)</auro-menuoption>
<auro-menuoption value="Springfield, IL (SPI-Capital)" id="Springfield, IL (SPI-Capital)" suggest="Springfield, IL (SPI-Capital)">Springfield, IL (SPI-Capital)</auro-menuoption>
<auro-menuoption value="Springfield, MO (SGF-Springfield Branson Regional)" id="Springfield, MO (SGF-Springfield Branson Regional)" suggest="Springfield, MO (SGF-Springfield Branson Regional)">Springfield, MO (SGF-Springfield Branson Regional)</auro-menuoption>
<auro-menuoption value="St. George, UT (SGU-St. George)" id="St. George, UT (SGU-St. George)" suggest="St. George, UT (SGU-St. George)">St. George, UT (SGU-St. George)</auro-menuoption>
<auro-menuoption value="St. Louis, MO (STL-Lambert/St.  Louis Intl.)" id="St. Louis, MO (STL-Lambert/St.  Louis Intl.)" suggest="St. Louis, MO (STL-Lambert/St.  Louis Intl.)">St. Louis, MO (STL-Lambert/St.  Louis Intl.)</auro-menuoption>
<auro-menuoption value="St. Marys, AK (KSM-St. Marys)" id="St. Marys, AK (KSM-St. Marys)" suggest="St. Marys, AK (KSM-St. Marys)">St. Marys, AK (KSM-St. Marys)</auro-menuoption>
<auro-menuoption value="St. Paul Island, AK (SNP-St. Paul Island)" id="St. Paul Island, AK (SNP-St. Paul Island)" suggest="St. Paul Island, AK (SNP-St. Paul Island)">St. Paul Island, AK (SNP-St. Paul Island)</auro-menuoption>
<auro-menuoption value="State College, PA (SCE-University Park)" id="State College, PA (SCE-University Park)" suggest="State College, PA (SCE-University Park)">State College, PA (SCE-University Park)</auro-menuoption>
<auro-menuoption value="Steamboat Springs, CO (HDN-Hayden)" id="Steamboat Springs, CO (HDN-Hayden)" suggest="Steamboat Springs, CO (HDN-Hayden)">Steamboat Springs, CO (HDN-Hayden)</auro-menuoption>
<auro-menuoption value="Stillwater, OK (SWO-Stillwater)" id="Stillwater, OK (SWO-Stillwater)" suggest="Stillwater, OK (SWO-Stillwater)">Stillwater, OK (SWO-Stillwater)</auro-menuoption>
<auro-menuoption value="Sun Valley, ID (SUN-Friedman Memorial)" id="Sun Valley, ID (SUN-Friedman Memorial)" suggest="Sun Valley, ID (SUN-Friedman Memorial)">Sun Valley, ID (SUN-Friedman Memorial)</auro-menuoption>
<auro-menuoption value="Syracuse, NY (SYR-Hancock Intl.)" id="Syracuse, NY (SYR-Hancock Intl.)" suggest="Syracuse, NY (SYR-Hancock Intl.)">Syracuse, NY (SYR-Hancock Intl.)</auro-menuoption>
<auro-menuoption value="Tallahassee, FL (TLH-Tallahassee Regional)" id="Tallahassee, FL (TLH-Tallahassee Regional)" suggest="Tallahassee, FL (TLH-Tallahassee Regional)">Tallahassee, FL (TLH-Tallahassee Regional)</auro-menuoption>
<auro-menuoption value="Tampa, FL (TPA-Tampa Intl.)" id="Tampa, FL (TPA-Tampa Intl.)" suggest="Tampa, FL (TPA-Tampa Intl.)">Tampa, FL (TPA-Tampa Intl.)</auro-menuoption>
<auro-menuoption value="Texarkana, AR (TXK-Texarkana Regional)" id="Texarkana, AR (TXK-Texarkana Regional)" suggest="Texarkana, AR (TXK-Texarkana Regional)">Texarkana, AR (TXK-Texarkana Regional)</auro-menuoption>
<auro-menuoption value="Toledo, OH (TOL-Toledo Express)" id="Toledo, OH (TOL-Toledo Express)" suggest="Toledo, OH (TOL-Toledo Express)">Toledo, OH (TOL-Toledo Express)</auro-menuoption>
<auro-menuoption value="Toronto, ON, Canada (YYZ-Pearson)" id="Toronto, ON, Canada (YYZ-Pearson)" suggest="Toronto, ON, Canada (YYZ-Pearson)">Toronto, ON, Canada (YYZ-Pearson)</auro-menuoption>
<auro-menuoption value="Torreon, Mexico (TRC-Torreon)" id="Torreon, Mexico (TRC-Torreon)" suggest="Torreon, Mexico (TRC-Torreon)">Torreon, Mexico (TRC-Torreon)</auro-menuoption>
<auro-menuoption value="Traverse City, MI (TVC-Cherry Capital)" id="Traverse City, MI (TVC-Cherry Capital)" suggest="Traverse City, MI (TVC-Cherry Capital)">Traverse City, MI (TVC-Cherry Capital)</auro-menuoption>
<auro-menuoption value="Tri-City, TN (TRI-Tri-City Regional)" id="Tri-City, TN (TRI-Tri-City Regional)" suggest="Tri-City, TN (TRI-Tri-City Regional)">Tri-City, TN (TRI-Tri-City Regional)</auro-menuoption>
<auro-menuoption value="Tucson, AZ (TUS-Tucson Intl.)" id="Tucson, AZ (TUS-Tucson Intl.)" suggest="Tucson, AZ (TUS-Tucson Intl.)">Tucson, AZ (TUS-Tucson Intl.)</auro-menuoption>
<auro-menuoption value="Tulsa, OK (TUL-Tulsa Intl.)" id="Tulsa, OK (TUL-Tulsa Intl.)" suggest="Tulsa, OK (TUL-Tulsa Intl.)">Tulsa, OK (TUL-Tulsa Intl.)</auro-menuoption>
<auro-menuoption value="Twin Falls, ID (TWF-Twin Falls)" id="Twin Falls, ID (TWF-Twin Falls)" suggest="Twin Falls, ID (TWF-Twin Falls)">Twin Falls, ID (TWF-Twin Falls)</auro-menuoption>
<auro-menuoption value="Tyler, TX (TYR-Pounds Field)" id="Tyler, TX (TYR-Pounds Field)" suggest="Tyler, TX (TYR-Pounds Field)">Tyler, TX (TYR-Pounds Field)</auro-menuoption>
<auro-menuoption value="Unalakleet, AK (UNK-Unalakleet)" id="Unalakleet, AK (UNK-Unalakleet)" suggest="Unalakleet, AK (UNK-Unalakleet)">Unalakleet, AK (UNK-Unalakleet)</auro-menuoption>
<auro-menuoption value="Urbana, IL (CMI-University Of Illinois/Willard)" id="Urbana, IL (CMI-University Of Illinois/Willard)" suggest="Urbana, IL (CMI-University Of Illinois/Willard)">Urbana, IL (CMI-University Of Illinois/Willard)</auro-menuoption>
<auro-menuoption value="Vail, CO (EGE-Eagle County)" id="Vail, CO (EGE-Eagle County)" suggest="Vail, CO (EGE-Eagle County)">Vail, CO (EGE-Eagle County)</auro-menuoption>
<auro-menuoption value="Valdez, AK (VDZ-Valdez)" id="Valdez, AK (VDZ-Valdez)" suggest="Valdez, AK (VDZ-Valdez)">Valdez, AK (VDZ-Valdez)</auro-menuoption>
<auro-menuoption value="Valdosta, GA (VLD-Valdosta Regional)" id="Valdosta, GA (VLD-Valdosta Regional)" suggest="Valdosta, GA (VLD-Valdosta Regional)">Valdosta, GA (VLD-Valdosta Regional)</auro-menuoption>
<auro-menuoption value="Vancouver, BC, Canada (YVR-Vancouver Intl.)" id="Vancouver, BC, Canada (YVR-Vancouver Intl.)" suggest="Vancouver, BC, Canada (YVR-Vancouver Intl.)">Vancouver, BC, Canada (YVR-Vancouver Intl.)</auro-menuoption>
<auro-menuoption value="Victoria, BC, Canada (YYJ-Victoria Int\u0027l Airport)" id="Victoria, BC, Canada (YYJ-Victoria Int\u0027l Airport)" suggest="Victoria, BC, Canada (YYJ-Victoria Int\u0027l Airport)">Victoria, BC, Canada (YYJ-Victoria Int\u0027l Airport)</auro-menuoption>
<auro-menuoption value="Waco, TX (ACT-Waco Regional)" id="Waco, TX (ACT-Waco Regional)" suggest="Waco, TX (ACT-Waco Regional)">Waco, TX (ACT-Waco Regional)</auro-menuoption>
<auro-menuoption value="Walla Walla, WA (ALW-Walla Walla Regional)" id="Walla Walla, WA (ALW-Walla Walla Regional)" suggest="Walla Walla, WA (ALW-Walla Walla Regional)">Walla Walla, WA (ALW-Walla Walla Regional)</auro-menuoption>
<auro-menuoption value="Washington, DC (WAS-All Airports)" id="Washington, DC (WAS-All Airports)" suggest="Washington, DC (WAS-All Airports)">Washington, DC (WAS-All Airports)</auro-menuoption>
<auro-menuoption value="Washington, DC (BWI-Baltimore Washington)" id="Washington, DC (BWI-Baltimore Washington)" suggest="Washington, DC (BWI-Baltimore Washington)">Washington, DC (BWI-Baltimore Washington)</auro-menuoption>
<auro-menuoption value="Washington, DC (DCA-Reagan National)" id="Washington, DC (DCA-Reagan National)" suggest="Washington, DC (DCA-Reagan National)">Washington, DC (DCA-Reagan National)</auro-menuoption>
<auro-menuoption value="Washington, DC (IAD-Dulles)" id="Washington, DC (IAD-Dulles)" suggest="Washington, DC (IAD-Dulles)">Washington, DC (IAD-Dulles)</auro-menuoption>
<auro-menuoption value="Waterloo, IA (ALO-Waterloo Municipal)" id="Waterloo, IA (ALO-Waterloo Municipal)" suggest="Waterloo, IA (ALO-Waterloo Municipal)">Waterloo, IA (ALO-Waterloo Municipal)</auro-menuoption>
<auro-menuoption value="Watertown, NY (ART-Watertown)" id="Watertown, NY (ART-Watertown)" suggest="Watertown, NY (ART-Watertown)">Watertown, NY (ART-Watertown)</auro-menuoption>
<auro-menuoption value="Wausau, WI (CWA-Cen. WI Regional)" id="Wausau, WI (CWA-Cen. WI Regional)" suggest="Wausau, WI (CWA-Cen. WI Regional)">Wausau, WI (CWA-Cen. WI Regional)</auro-menuoption>
<auro-menuoption value="Wenatchee, WA (EAT-Pangborn Field)" id="Wenatchee, WA (EAT-Pangborn Field)" suggest="Wenatchee, WA (EAT-Pangborn Field)">Wenatchee, WA (EAT-Pangborn Field)</auro-menuoption>
<auro-menuoption value="West Palm Beach, FL (PBI-Palm Beach Intl.)" id="West Palm Beach, FL (PBI-Palm Beach Intl.)" suggest="West Palm Beach, FL (PBI-Palm Beach Intl.)">West Palm Beach, FL (PBI-Palm Beach Intl.)</auro-menuoption>
<auro-menuoption value="West Yellowstone, MT (WYS-West Yellowstone)" id="West Yellowstone, MT (WYS-West Yellowstone)" suggest="West Yellowstone, MT (WYS-West Yellowstone)">West Yellowstone, MT (WYS-West Yellowstone)</auro-menuoption>
<auro-menuoption value="White Plains, NY (HPN-Westchester Co.)" id="White Plains, NY (HPN-Westchester Co.)" suggest="White Plains, NY (HPN-Westchester Co.)">White Plains, NY (HPN-Westchester Co.)</auro-menuoption>
<auro-menuoption value="Wichita Falls, TX (SPS-Sheppard Air Force Base)" id="Wichita Falls, TX (SPS-Sheppard Air Force Base)" suggest="Wichita Falls, TX (SPS-Sheppard Air Force Base)">Wichita Falls, TX (SPS-Sheppard Air Force Base)</auro-menuoption>
<auro-menuoption value="Wichita, KS (ICT-Dwight D. Eisenhower National)" id="Wichita, KS (ICT-Dwight D. Eisenhower National)" suggest="Wichita, KS (ICT-Dwight D. Eisenhower National)">Wichita, KS (ICT-Dwight D. Eisenhower National)</auro-menuoption>
<auro-menuoption value="Wilkes-Barre, PA (AVP-Wilkes-Barre Scranton Intl.)" id="Wilkes-Barre, PA (AVP-Wilkes-Barre Scranton Intl.)" suggest="Wilkes-Barre, PA (AVP-Wilkes-Barre Scranton Intl.)">Wilkes-Barre, PA (AVP-Wilkes-Barre Scranton Intl.)</auro-menuoption>
<auro-menuoption value="Wilmington, NC (ILM-Wilmington)" id="Wilmington, NC (ILM-Wilmington)" suggest="Wilmington, NC (ILM-Wilmington)">Wilmington, NC (ILM-Wilmington)</auro-menuoption>
<auro-menuoption value="Winnipeg, MB, Canada (YWG-Winnipeg Intl.)" id="Winnipeg, MB, Canada (YWG-Winnipeg Intl.)" suggest="Winnipeg, MB, Canada (YWG-Winnipeg Intl.)">Winnipeg, MB, Canada (YWG-Winnipeg Intl.)</auro-menuoption>
<auro-menuoption value="Worcester, MA (ORH-Worcester)" id="Worcester, MA (ORH-Worcester)" suggest="Worcester, MA (ORH-Worcester)">Worcester, MA (ORH-Worcester)</auro-menuoption>
<auro-menuoption value="Wrangell, AK (WRG-Wrangell)" id="Wrangell, AK (WRG-Wrangell)" suggest="Wrangell, AK (WRG-Wrangell)">Wrangell, AK (WRG-Wrangell)</auro-menuoption>
<auro-menuoption value="Yakima, WA (YKM-Yakima Air Terminal)" id="Yakima, WA (YKM-Yakima Air Terminal)" suggest="Yakima, WA (YKM-Yakima Air Terminal)">Yakima, WA (YKM-Yakima Air Terminal)</auro-menuoption>
<auro-menuoption value="Yakutat, AK (YAK-Yakutat)" id="Yakutat, AK (YAK-Yakutat)" suggest="Yakutat, AK (YAK-Yakutat)">Yakutat, AK (YAK-Yakutat)</auro-menuoption>
<auro-menuoption value="Yosemite, CA (FAT-Fresno Air Terminal)" id="Yosemite, CA (FAT-Fresno Air Terminal)" suggest="Yosemite, CA (FAT-Fresno Air Terminal)">Yosemite, CA (FAT-Fresno Air Terminal)</auro-menuoption>
<auro-menuoption value="Yuma, AZ (YUM-Yuma Intl.)" id="Yuma, AZ (YUM-Yuma Intl.)" suggest="Yuma, AZ (YUM-Yuma Intl.)">Yuma, AZ (YUM-Yuma Intl.)</auro-menuoption>
<auro-menuoption value="Zacatecas, Mexico (ZCL-Zacatecas)" id="Zacatecas, Mexico (ZCL-Zacatecas)" suggest="Zacatecas, Mexico (ZCL-Zacatecas)">Zacatecas, Mexico (ZCL-Zacatecas)</auro-menuoption>
<auro-menuoption value="Zihuatanejo, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)" id="Zihuatanejo, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)" suggest="Zihuatanejo, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)">Zihuatanejo, Mexico (ZIH-Ixtapa/Zihuatanejo Intl.)</auro-menuoption>